//! Manual deploy backend.
//!
//! Instead of calling a cloud API, this generates a deploy bundle
//! (Dockerfile + .env + README) in `.roko/deploy-bundles/{name}/`
//! that the user can manually deploy anywhere.

use std::path::PathBuf;

use anyhow::{Context, Result};
use async_trait::async_trait;
use chrono::Utc;
use tracing::info;

use super::{DeployBackend, DeploySpec, Deployment, DeploymentStatus};

/// Deploy backend that writes a local deploy bundle.
pub struct ManualBackend {
    /// Root directory for bundles (default: `.roko/deploy-bundles/`).
    bundles_dir: PathBuf,
}

impl Default for ManualBackend {
    fn default() -> Self {
        Self {
            bundles_dir: PathBuf::from(".roko/deploy-bundles"),
        }
    }
}

#[async_trait]
impl DeployBackend for ManualBackend {
    async fn deploy(&self, spec: &DeploySpec) -> Result<Deployment> {
        let bundle_dir = self.bundles_dir.join(&spec.name);
        std::fs::create_dir_all(&bundle_dir).context("create deploy bundle directory")?;

        // Write .env file
        let env_contents: String = spec
            .env_vars
            .iter()
            .map(|(k, v)| format!("{k}={v}"))
            .collect::<Vec<_>>()
            .join("\n");
        std::fs::write(bundle_dir.join(".env"), &env_contents).context("write .env")?;

        // Write Dockerfile
        let dockerfile = format!(
            "FROM {image}\nENV PORT=8080\nEXPOSE 8080\nCMD [\"roko\", \"worker\"]\n",
            image = spec.image,
        );
        std::fs::write(bundle_dir.join("Dockerfile"), &dockerfile).context("write Dockerfile")?;

        // Write README
        let readme = format!(
            "# Deploy Bundle: {name}\n\n\
             Generated by `roko serve` at {ts}\n\n\
             ## Deploy\n\n\
             ```bash\n\
             cd {dir}\n\
             docker build -t {name} .\n\
             docker run --env-file .env -p 8080:8080 {name}\n\
             ```\n",
            name = spec.name,
            ts = Utc::now().to_rfc3339(),
            dir = bundle_dir.display(),
        );
        std::fs::write(bundle_dir.join("README.md"), &readme).context("write README.md")?;

        let id = format!("manual-{}", uuid::Uuid::new_v4());
        let bundle_path = bundle_dir.display().to_string();

        info!(name = %spec.name, path = %bundle_path, "generated deploy bundle");

        Ok(Deployment {
            id,
            name: spec.name.clone(),
            status: DeploymentStatus::Ready {
                url: format!("file://{bundle_path}"),
            },
            url: Some(format!("file://{bundle_path}")),
            created_at: Utc::now(),
        })
    }

    async fn status(&self, deployment_id: &str) -> Result<DeploymentStatus> {
        // Manual deployments are always "ready" (it's just files on disk)
        let name = deployment_id
            .strip_prefix("manual-")
            .unwrap_or(deployment_id);
        let bundle_dir = self.bundles_dir.join(name);

        if bundle_dir.exists() {
            Ok(DeploymentStatus::Ready {
                url: format!("file://{}", bundle_dir.display()),
            })
        } else {
            Ok(DeploymentStatus::TornDown)
        }
    }

    async fn teardown(&self, deployment_id: &str) -> Result<()> {
        // Try to find the bundle by ID suffix or name
        let name = deployment_id
            .strip_prefix("manual-")
            .unwrap_or(deployment_id);
        let bundle_dir = self.bundles_dir.join(name);

        if bundle_dir.exists() {
            std::fs::remove_dir_all(&bundle_dir).context("remove deploy bundle")?;
            info!(%deployment_id, "removed deploy bundle");
        }
        Ok(())
    }

    async fn logs(&self, _deployment_id: &str, _tail: usize) -> Result<Vec<String>> {
        Ok(vec![
            "Manual backend: no runtime logs available. Check Docker logs directly.".into(),
        ])
    }
}
