//! Neutral value types for plan generation (#280).
//!
//! Plans are generated by `roko_cli::prd::generate_plan` (gap-2623b2), the one
//! pipeline every caller uses: `roko prd plan`, `roko plan generate`,
//! `roko do`, plan regeneration and serve. The `PlanGenerator` service trait
//! #280 sketched here was never implemented or called, so it was removed
//! (find-84bfa8). The value types below remain for `roko-cli`'s
//! `DefaultPlanGenerator`, a validation pipeline only its tests exercise.
//!
//! # Call-site manifest
//!
//! See [`adapter_keys`] for the canonical list of call sites that will be
//! migrated by #283.

use std::path::{Path, PathBuf};

use roko_learn::runtime_feedback::{ArtifactValidationReport, GenerationOutcome};
use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Call-site manifest (§ "Mechanical Call-Site Manifest" from #280)
// ---------------------------------------------------------------------------

/// Each row from the #280 manifest. Callers reference these keys to identify
/// themselves when building adapter implementations for #283.
pub mod adapter_keys {
    /// `prd.rs::generate_plan_from_prd` — default PRD path.
    pub const PRD_DEFAULT: &str = "prd_default";
    /// `generate_plan_from_prd_with_model` — PRD + explicit model override.
    pub const PRD_MODEL: &str = "prd_model";
    /// `generate_plan_from_prd_with_failure_context` — PRD + gate-failure context.
    pub const PRD_REPLAN: &str = "prd_replan";
    /// `commands/plan.rs` — plan generate from prompt or file.
    pub const PLAN_GENERATE: &str = "plan_generate";
    /// `commands/do_cmd.rs` — direct plan-generation path.
    pub const DO_STANDARD: &str = "do_standard";
    /// `do_cmd.rs` — PRD-first path.
    pub const DO_COMPLEX: &str = "do_complex";
    /// `serve_runtime.rs::generate_plan_from_prd` (CLI-side).
    pub const CLI_SERVE_RUNTIME: &str = "cli_serve_runtime";
    /// `roko-serve/src/runtime.rs::generate_plan_from_prd` + `job_runner.rs`.
    pub const SERVE_RUNTIME: &str = "serve_runtime";
    /// `roko-serve/src/routes/plans.rs::generate_plan`.
    pub const SERVE_HTTP: &str = "serve_http";
    /// Gate-failure replan source — triggered by the graph engine when a gate
    /// fails and `replan_on_gate_failure` is enabled. Owned by #252/#275.
    pub const GATE_REPLAN: &str = "gate_replan";
}

// ---------------------------------------------------------------------------
// PlanSource
// ---------------------------------------------------------------------------

/// Where the generation request originates.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum PlanSource {
    /// Generated from a published PRD file.
    Prd {
        /// PRD slug (used as plan directory name).
        slug: String,
        /// Path to the PRD markdown file.
        prd_path: PathBuf,
    },
    /// Generated from a user-supplied prompt string.
    Prompt {
        /// Freeform prompt text.
        prompt: String,
    },
    /// Generated from a local file (notes, spec, etc.).
    File {
        /// Path to the source file.
        path: PathBuf,
    },
    /// Replan: previous generation failed and this is a corrective pass.
    Replan {
        /// Original PRD slug.
        slug: String,
        /// Path to the PRD file.
        prd_path: PathBuf,
        /// Failure context injected into the system prompt.
        failure_context: String,
    },
}

impl PlanSource {
    /// Canonical slug for plan directory naming.
    #[must_use]
    pub fn slug(&self) -> &str {
        match self {
            Self::Prd { slug, .. } | Self::Replan { slug, .. } => slug,
            Self::Prompt { .. } => "prompt",
            Self::File { path } => path.file_stem().and_then(|s| s.to_str()).unwrap_or("file"),
        }
    }

    /// Whether this source carries failure context for replanning.
    #[must_use]
    pub fn has_failure_context(&self) -> bool {
        matches!(self, Self::Replan { .. })
    }

    /// Failure context text, if present.
    #[must_use]
    pub fn failure_context(&self) -> Option<&str> {
        match self {
            Self::Replan {
                failure_context, ..
            } => Some(failure_context.as_str()),
            _ => None,
        }
    }
}

// ---------------------------------------------------------------------------
// Request / Overrides
// ---------------------------------------------------------------------------

/// Model/role/tool-policy overrides the caller can supply.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PlanGeneratorOverrides {
    /// Explicit model key (skips cascade routing selection).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// Override the default `"strategist"` role.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    /// Allowed tools for the generation agent (comma-separated).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub allowed_tools: Option<String>,
    /// Plan template kind override.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub template: Option<String>,
    /// Maximum USD budget for the generation call.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub budget_usd: Option<f64>,
    /// Maximum repair/retry attempts (defaults to [`DEFAULT_REPAIR_CAP`]).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub repair_cap: Option<u32>,
}

/// A plan-generation request: its source, workspace, caller and overrides.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanGeneratorRequest {
    /// Where the plan content originates.
    pub source: PlanSource,
    /// Workspace root directory.
    pub workdir: PathBuf,
    /// Caller-specific adapter key from [`adapter_keys`].
    pub adapter_key: String,
    /// Optional overrides for model, role, tools, template, budget.
    #[serde(default)]
    pub overrides: PlanGeneratorOverrides,
    /// Whether this is a dry-run (no persistence).
    #[serde(default)]
    pub dry_run: bool,
}

// ---------------------------------------------------------------------------
// Validation evidence
// ---------------------------------------------------------------------------

/// Validation evidence produced by the extraction pipeline.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ValidationEvidence {
    /// Number of TOML extraction attempts.
    pub extraction_attempts: u32,
    /// Whether model escalation was triggered.
    pub model_escalated: bool,
    /// Final model used for generation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub final_model: Option<String>,
    /// Repair operations applied to the TOML.
    pub repairs_applied: Vec<String>,
    /// Policy violations detected (may be empty if all passed).
    pub policy_violations: Vec<String>,
}

// ---------------------------------------------------------------------------
// Outcome
// ---------------------------------------------------------------------------

/// The normalized outcome from a generation request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanGeneratorOutcome {
    /// The validated tasks.toml content (absent on total failure).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tasks_toml: Option<String>,
    /// Optional plan.md narrative content.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub plan_md: Option<String>,
    /// Slug used for the plan directory.
    pub slug: String,
    /// Generation outcome (process + artifact status).
    pub outcome: GenerationOutcome,
    /// Validation evidence from the extraction pipeline.
    pub evidence: ValidationEvidence,
    /// Task count in the generated plan (0 on failure).
    pub task_count: usize,
    /// Estimated complexity label.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub estimated_complexity: Option<String>,
    /// Provenance: which adapter key triggered this generation.
    pub adapter_key: String,
}

impl PlanGeneratorOutcome {
    /// True only when generation produced a valid, policy-conforming plan.
    #[must_use]
    pub fn is_success(&self) -> bool {
        self.tasks_toml.is_some() && self.outcome.fully_successful()
    }

    /// True when the process ran but the artifact failed validation.
    #[must_use]
    pub fn is_partial(&self) -> bool {
        self.outcome.process_success && !self.outcome.artifact_valid
    }
}

// ---------------------------------------------------------------------------
// Adapter trait (host callback contract for #283)
// ---------------------------------------------------------------------------

/// Contract that each call-site adapter implements for #283.
///
/// The generator owns generation, repair, validation, and the normalized
/// outcome. Each adapter owns:
/// - Source loading and authorization
/// - Persistence destination
/// - Execution trigger
/// - User rendering / progress reporting
///
/// This trait is object-safe so adapters can be boxed.
pub trait PlanGeneratorAdapter: Send + Sync {
    /// Adapter key from [`adapter_keys`].
    fn adapter_key(&self) -> &str;

    /// Persist the generated plan to disk or storage.
    ///
    /// Called only when the outcome contains valid `tasks_toml`.
    /// Returns the path where the plan was written.
    fn persist(&self, outcome: &PlanGeneratorOutcome, workdir: &Path) -> anyhow::Result<PathBuf>;

    /// Optional post-generation execution trigger.
    ///
    /// Called after successful persistence. Adapters that auto-execute plans
    /// implement this; others return `Ok(())`.
    fn on_persisted(
        &self,
        _outcome: &PlanGeneratorOutcome,
        _plan_path: &Path,
    ) -> anyhow::Result<()> {
        Ok(())
    }

    /// Report progress or status to the user.
    ///
    /// Called at various stages of generation for adapters that render UI.
    fn report(&self, _message: &str) {}
}

// ---------------------------------------------------------------------------
// Default repair cap
// ---------------------------------------------------------------------------

/// Default maximum repair/extraction retry attempts.
pub const DEFAULT_REPAIR_CAP: u32 = 2;

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/// Plan generation errors.
#[derive(Debug, thiserror::Error)]
pub enum PlanGenError {
    /// TOML extraction/validation failed after all repair attempts.
    #[error("plan validation failed: {reason}")]
    ValidationFailed {
        /// Description of the validation failure.
        reason: String,
    },
    /// Provider dispatch failed.
    #[error("provider dispatch failed: {0}")]
    DispatchFailed(#[from] anyhow::Error),
    /// Budget exceeded.
    #[error("budget exceeded: spent ${spent_usd:.4} of ${budget_usd:.4} limit")]
    BudgetExceeded {
        /// Actual USD spent.
        spent_usd: f64,
        /// Configured USD budget limit.
        budget_usd: f64,
    },
}

/// Intermediate result from plan validation.
#[derive(Debug, Clone)]
pub struct ValidatedPlan {
    /// The validated and repaired TOML content.
    pub tasks_toml: String,
    /// Optional plan.md narrative.
    pub plan_md: Option<String>,
    /// Number of tasks in the plan.
    pub task_count: usize,
    /// Repairs applied during validation.
    pub repairs: Vec<String>,
    /// Policy violations (empty if all passed).
    pub policy_violations: Vec<String>,
}

// ---------------------------------------------------------------------------
// Outcome constructors
// ---------------------------------------------------------------------------

/// Build a [`PlanGeneratorOutcome`] for a successful generation.
#[must_use]
pub fn success_outcome(
    request: &PlanGeneratorRequest,
    validated: ValidatedPlan,
    evidence: ValidationEvidence,
    validation_report: Option<ArtifactValidationReport>,
) -> PlanGeneratorOutcome {
    PlanGeneratorOutcome {
        tasks_toml: Some(validated.tasks_toml),
        plan_md: validated.plan_md,
        slug: request.source.slug().to_string(),
        outcome: GenerationOutcome {
            process_success: true,
            artifact_valid: true,
            validation_report,
            spec_quality: None,
        },
        evidence,
        task_count: validated.task_count,
        estimated_complexity: None,
        adapter_key: request.adapter_key.clone(),
    }
}

/// Build a [`PlanGeneratorOutcome`] for a failed generation.
#[must_use]
pub fn failure_outcome(
    request: &PlanGeneratorRequest,
    evidence: ValidationEvidence,
) -> PlanGeneratorOutcome {
    PlanGeneratorOutcome {
        tasks_toml: None,
        plan_md: None,
        slug: request.source.slug().to_string(),
        outcome: GenerationOutcome {
            process_success: false,
            artifact_valid: false,
            validation_report: None,
            spec_quality: None,
        },
        evidence,
        task_count: 0,
        estimated_complexity: None,
        adapter_key: request.adapter_key.clone(),
    }
}

/// Build a [`PlanGeneratorOutcome`] for a partial success (process ran but
/// artifact validation failed).
#[must_use]
pub fn partial_outcome(
    request: &PlanGeneratorRequest,
    evidence: ValidationEvidence,
) -> PlanGeneratorOutcome {
    PlanGeneratorOutcome {
        tasks_toml: None,
        plan_md: None,
        slug: request.source.slug().to_string(),
        outcome: GenerationOutcome {
            process_success: true,
            artifact_valid: false,
            validation_report: None,
            spec_quality: None,
        },
        evidence,
        task_count: 0,
        estimated_complexity: None,
        adapter_key: request.adapter_key.clone(),
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // ---- PlanSource tests ----

    #[test]
    fn plan_source_prd_slug() {
        let source = PlanSource::Prd {
            slug: "my-feature".to_string(),
            prd_path: PathBuf::from("/tmp/prd.md"),
        };
        assert_eq!(source.slug(), "my-feature");
        assert!(!source.has_failure_context());
        assert!(source.failure_context().is_none());
    }

    #[test]
    fn plan_source_prompt_slug() {
        let source = PlanSource::Prompt {
            prompt: "build a widget".to_string(),
        };
        assert_eq!(source.slug(), "prompt");
    }

    #[test]
    fn plan_source_file_slug() {
        let source = PlanSource::File {
            path: PathBuf::from("/tmp/my-notes.md"),
        };
        assert_eq!(source.slug(), "my-notes");
    }

    #[test]
    fn plan_source_replan_has_failure_context() {
        let source = PlanSource::Replan {
            slug: "my-feature".to_string(),
            prd_path: PathBuf::from("/tmp/prd.md"),
            failure_context: "gate failure on T2".to_string(),
        };
        assert_eq!(source.slug(), "my-feature");
        assert!(source.has_failure_context());
        assert_eq!(source.failure_context(), Some("gate failure on T2"));
    }

    // ---- PlanGeneratorOutcome tests ----

    fn make_evidence() -> ValidationEvidence {
        ValidationEvidence {
            extraction_attempts: 1,
            model_escalated: false,
            final_model: None,
            repairs_applied: vec![],
            policy_violations: vec![],
        }
    }

    #[test]
    fn outcome_success_requires_toml_and_valid_outcome() {
        let outcome = PlanGeneratorOutcome {
            tasks_toml: Some("[meta]\nplan = \"test\"\n".to_string()),
            plan_md: None,
            slug: "test".to_string(),
            outcome: GenerationOutcome {
                process_success: true,
                artifact_valid: true,
                validation_report: None,
                spec_quality: None,
            },
            evidence: make_evidence(),
            task_count: 2,
            estimated_complexity: None,
            adapter_key: "test".to_string(),
        };
        assert!(outcome.is_success());
        assert!(!outcome.is_partial());
    }

    #[test]
    fn outcome_partial_when_process_succeeded_but_artifact_invalid() {
        let outcome = PlanGeneratorOutcome {
            tasks_toml: None,
            plan_md: None,
            slug: "test".to_string(),
            outcome: GenerationOutcome {
                process_success: true,
                artifact_valid: false,
                validation_report: None,
                spec_quality: None,
            },
            evidence: ValidationEvidence {
                extraction_attempts: 3,
                model_escalated: true,
                final_model: Some("claude-opus-4-6".to_string()),
                repairs_applied: vec![],
                policy_violations: vec!["too many tasks".to_string()],
            },
            task_count: 0,
            estimated_complexity: None,
            adapter_key: "test".to_string(),
        };
        assert!(!outcome.is_success());
        assert!(outcome.is_partial());
    }

    #[test]
    fn outcome_failure_when_process_failed() {
        let outcome = PlanGeneratorOutcome {
            tasks_toml: None,
            plan_md: None,
            slug: "test".to_string(),
            outcome: GenerationOutcome {
                process_success: false,
                artifact_valid: false,
                validation_report: None,
                spec_quality: None,
            },
            evidence: make_evidence(),
            task_count: 0,
            estimated_complexity: None,
            adapter_key: "test".to_string(),
        };
        assert!(!outcome.is_success());
        assert!(!outcome.is_partial());
    }

    // ---- Outcome constructor tests ----

    fn make_request(adapter_key: &str) -> PlanGeneratorRequest {
        PlanGeneratorRequest {
            source: PlanSource::Prd {
                slug: "test-slug".to_string(),
                prd_path: PathBuf::from("/tmp/test.md"),
            },
            workdir: PathBuf::from("/tmp/workspace"),
            adapter_key: adapter_key.to_string(),
            overrides: PlanGeneratorOverrides::default(),
            dry_run: false,
        }
    }

    #[test]
    fn success_outcome_has_toml_and_valid_flags() {
        let request = make_request("prd_default");
        let validated = ValidatedPlan {
            tasks_toml: "[meta]\nplan = \"test-slug\"\n".to_string(),
            plan_md: Some("# Plan".to_string()),
            task_count: 3,
            repairs: vec!["fixed slug".to_string()],
            policy_violations: vec![],
        };
        let evidence = make_evidence();
        let outcome = success_outcome(&request, validated, evidence, None);
        assert!(outcome.is_success());
        assert_eq!(outcome.task_count, 3);
        assert_eq!(outcome.slug, "test-slug");
        assert_eq!(outcome.adapter_key, "prd_default");
        assert!(outcome.plan_md.is_some());
    }

    #[test]
    fn failure_outcome_has_no_toml() {
        let request = make_request("do_standard");
        let evidence = make_evidence();
        let outcome = failure_outcome(&request, evidence);
        assert!(!outcome.is_success());
        assert!(!outcome.is_partial());
        assert!(outcome.tasks_toml.is_none());
        assert_eq!(outcome.adapter_key, "do_standard");
    }

    #[test]
    fn partial_outcome_process_success_artifact_invalid() {
        let request = make_request("serve_http");
        let evidence = make_evidence();
        let outcome = partial_outcome(&request, evidence);
        assert!(!outcome.is_success());
        assert!(outcome.is_partial());
        assert!(outcome.tasks_toml.is_none());
    }

    // ---- Default repair cap ----

    #[test]
    fn default_repair_cap_is_two() {
        assert_eq!(DEFAULT_REPAIR_CAP, 2);
    }

    #[test]
    fn overrides_repair_cap_overrides_default() {
        let overrides = PlanGeneratorOverrides {
            repair_cap: Some(5),
            ..Default::default()
        };
        assert_eq!(overrides.repair_cap.unwrap_or(DEFAULT_REPAIR_CAP), 5);
    }

    // ---- Adapter keys completeness ----

    #[test]
    fn adapter_keys_are_nonempty_and_unique() {
        let keys = [
            adapter_keys::PRD_DEFAULT,
            adapter_keys::PRD_MODEL,
            adapter_keys::PRD_REPLAN,
            adapter_keys::PLAN_GENERATE,
            adapter_keys::DO_STANDARD,
            adapter_keys::DO_COMPLEX,
            adapter_keys::CLI_SERVE_RUNTIME,
            adapter_keys::SERVE_RUNTIME,
            adapter_keys::SERVE_HTTP,
            adapter_keys::GATE_REPLAN,
        ];
        let mut seen = std::collections::HashSet::new();
        for key in &keys {
            assert!(!key.is_empty(), "adapter key must not be empty");
            assert!(seen.insert(*key), "duplicate adapter key: {key}");
        }
        assert_eq!(keys.len(), 10, "expected 10 adapter keys from manifest");
    }

    // ---- PlanGenError display ----

    #[test]
    fn plan_gen_error_display() {
        let err = PlanGenError::ValidationFailed {
            reason: "missing [meta]".to_string(),
        };
        assert!(err.to_string().contains("missing [meta]"));

        let err = PlanGenError::BudgetExceeded {
            spent_usd: 1.5,
            budget_usd: 1.0,
        };
        assert!(err.to_string().contains("1.5"));
    }

    // ---- Overrides behavior ----

    #[test]
    fn overrides_default_is_all_none() {
        let o = PlanGeneratorOverrides::default();
        assert!(o.model.is_none());
        assert!(o.role.is_none());
        assert!(o.allowed_tools.is_none());
        assert!(o.template.is_none());
        assert!(o.budget_usd.is_none());
        assert!(o.repair_cap.is_none());
    }

    #[test]
    fn overrides_model_and_role_propagate_to_request() {
        let request = PlanGeneratorRequest {
            source: PlanSource::Prompt {
                prompt: "build widget".to_string(),
            },
            workdir: PathBuf::from("/tmp"),
            adapter_key: adapter_keys::DO_STANDARD.to_string(),
            overrides: PlanGeneratorOverrides {
                model: Some("claude-sonnet-4-6".to_string()),
                role: Some("architect".to_string()),
                budget_usd: Some(2.0),
                ..Default::default()
            },
            dry_run: false,
        };
        assert_eq!(
            request.overrides.model.as_deref(),
            Some("claude-sonnet-4-6")
        );
        assert_eq!(request.overrides.role.as_deref(), Some("architect"));
        assert_eq!(request.overrides.budget_usd, Some(2.0));
    }

    #[test]
    fn overrides_budget_zero_is_valid() {
        let o = PlanGeneratorOverrides {
            budget_usd: Some(0.0),
            ..Default::default()
        };
        assert_eq!(o.budget_usd, Some(0.0));
    }

    // ---- Budget enforcement (error shape) ----

    #[test]
    fn budget_exceeded_error_includes_both_amounts() {
        let err = PlanGenError::BudgetExceeded {
            spent_usd: 3.1415,
            budget_usd: 2.0,
        };
        let msg = err.to_string();
        assert!(msg.contains("3.1415"), "must include spent: {msg}");
        assert!(msg.contains("2.0"), "must include budget: {msg}");
    }

    #[test]
    fn dispatch_failed_wraps_anyhow() {
        let inner = anyhow::anyhow!("provider timed out");
        let err = PlanGenError::DispatchFailed(inner);
        assert!(
            err.to_string().contains("provider timed out"),
            "must wrap inner: {}",
            err
        );
    }

    // ---- Validation evidence ----

    #[test]
    fn evidence_with_escalation_and_repairs() {
        let evidence = ValidationEvidence {
            extraction_attempts: 3,
            model_escalated: true,
            final_model: Some("claude-opus-4-6".to_string()),
            repairs_applied: vec![
                "fixed missing [meta]".to_string(),
                "normalized task ids".to_string(),
            ],
            policy_violations: vec!["task count exceeds 50".to_string()],
        };
        assert!(evidence.model_escalated);
        assert_eq!(evidence.extraction_attempts, 3);
        assert_eq!(evidence.repairs_applied.len(), 2);
        assert_eq!(evidence.policy_violations.len(), 1);
    }

    // ---- Adapter contract tests ----

    struct TestAdapter {
        key: &'static str,
        persist_err: bool,
    }

    impl PlanGeneratorAdapter for TestAdapter {
        fn adapter_key(&self) -> &str {
            self.key
        }

        fn persist(
            &self,
            outcome: &PlanGeneratorOutcome,
            workdir: &Path,
        ) -> anyhow::Result<PathBuf> {
            if self.persist_err {
                anyhow::bail!("disk full");
            }
            Ok(workdir.join("plans").join(&outcome.slug))
        }

        fn report(&self, _message: &str) {
            // no-op in test
        }
    }

    #[test]
    fn adapter_persist_returns_plan_path() {
        let adapter = TestAdapter {
            key: adapter_keys::PRD_DEFAULT,
            persist_err: false,
        };
        let request = make_request(adapter.adapter_key());
        let validated = ValidatedPlan {
            tasks_toml: "[meta]\nplan = \"test-slug\"\n".to_string(),
            plan_md: None,
            task_count: 1,
            repairs: vec![],
            policy_violations: vec![],
        };
        let outcome = success_outcome(&request, validated, make_evidence(), None);
        let path = adapter
            .persist(&outcome, &request.workdir)
            .expect("persist should succeed");
        assert_eq!(path, PathBuf::from("/tmp/workspace/plans/test-slug"));
    }

    #[test]
    fn adapter_persist_error_propagates() {
        let adapter = TestAdapter {
            key: adapter_keys::SERVE_HTTP,
            persist_err: true,
        };
        let request = make_request(adapter.adapter_key());
        let outcome = failure_outcome(&request, make_evidence());
        let err = adapter
            .persist(&outcome, &request.workdir)
            .expect_err("should fail");
        assert!(err.to_string().contains("disk full"));
    }

    #[test]
    fn adapter_on_persisted_default_is_noop() {
        let adapter = TestAdapter {
            key: adapter_keys::DO_STANDARD,
            persist_err: false,
        };
        let request = make_request(adapter.adapter_key());
        let outcome = failure_outcome(&request, make_evidence());
        // Default on_persisted should succeed (no-op).
        adapter
            .on_persisted(&outcome, Path::new("/tmp/plan"))
            .expect("default on_persisted should be Ok");
    }

    // ---- No silent execution invariant ----

    #[test]
    fn outcome_does_not_contain_execution_state() {
        let request = make_request("prd_default");
        let validated = ValidatedPlan {
            tasks_toml: "[meta]\nplan = \"test-slug\"\n".to_string(),
            plan_md: None,
            task_count: 5,
            repairs: vec![],
            policy_violations: vec![],
        };
        let outcome = success_outcome(&request, validated, make_evidence(), None);
        // Serialize and verify no "execution" or "running" fields exist.
        let json = serde_json::to_value(&outcome).unwrap();
        assert!(
            json.get("execution_status").is_none(),
            "outcome must not carry execution state"
        );
        assert!(
            json.get("running").is_none(),
            "outcome must not carry running flag"
        );
    }

    // ---- Golden fixture: round-trip serialization ----

    #[test]
    fn golden_outcome_success_roundtrip() {
        let request = make_request(adapter_keys::PRD_DEFAULT);
        let validated = ValidatedPlan {
            tasks_toml: concat!(
                "[meta]\n",
                "plan = \"test-slug\"\n\n",
                "[[tasks]]\n",
                "id = \"T1\"\n",
                "title = \"Implement feature\"\n",
            )
            .to_string(),
            plan_md: Some("# Plan\nImplement the feature.".to_string()),
            task_count: 1,
            repairs: vec!["normalized ids".to_string()],
            policy_violations: vec![],
        };
        let evidence = ValidationEvidence {
            extraction_attempts: 2,
            model_escalated: false,
            final_model: Some("claude-sonnet-4-6".to_string()),
            repairs_applied: vec!["normalized ids".to_string()],
            policy_violations: vec![],
        };
        let outcome = success_outcome(&request, validated, evidence, None);
        let json = serde_json::to_string_pretty(&outcome).unwrap();
        let roundtrip: PlanGeneratorOutcome = serde_json::from_str(&json).unwrap();

        assert_eq!(roundtrip.slug, outcome.slug);
        assert_eq!(roundtrip.task_count, outcome.task_count);
        assert_eq!(roundtrip.tasks_toml, outcome.tasks_toml);
        assert_eq!(roundtrip.plan_md, outcome.plan_md);
        assert_eq!(roundtrip.adapter_key, outcome.adapter_key);
        assert!(roundtrip.is_success());
    }

    #[test]
    fn golden_outcome_failure_roundtrip() {
        let request = make_request(adapter_keys::SERVE_RUNTIME);
        let evidence = ValidationEvidence {
            extraction_attempts: 3,
            model_escalated: true,
            final_model: Some("claude-opus-4-6".to_string()),
            repairs_applied: vec!["attempted meta fix".to_string()],
            policy_violations: vec!["task count exceeds maximum".to_string()],
        };
        let outcome = failure_outcome(&request, evidence);
        let json = serde_json::to_string_pretty(&outcome).unwrap();
        let roundtrip: PlanGeneratorOutcome = serde_json::from_str(&json).unwrap();

        assert!(!roundtrip.is_success());
        assert!(!roundtrip.is_partial());
        assert!(roundtrip.tasks_toml.is_none());
        assert_eq!(roundtrip.evidence.extraction_attempts, 3);
        assert!(roundtrip.evidence.model_escalated);
        assert_eq!(roundtrip.evidence.policy_violations.len(), 1);
    }

    #[test]
    fn golden_outcome_partial_roundtrip() {
        let request = make_request(adapter_keys::DO_COMPLEX);
        let evidence = ValidationEvidence {
            extraction_attempts: 2,
            model_escalated: false,
            final_model: None,
            repairs_applied: vec![],
            policy_violations: vec![
                "missing verify commands".to_string(),
                "circular dependencies".to_string(),
            ],
        };
        let outcome = partial_outcome(&request, evidence);
        let json = serde_json::to_string_pretty(&outcome).unwrap();
        let roundtrip: PlanGeneratorOutcome = serde_json::from_str(&json).unwrap();

        assert!(!roundtrip.is_success());
        assert!(roundtrip.is_partial());
        assert_eq!(roundtrip.evidence.policy_violations.len(), 2);
    }

    // ---- Golden fixture: request serialization ----

    #[test]
    fn golden_request_with_overrides_roundtrip() {
        let request = PlanGeneratorRequest {
            source: PlanSource::Replan {
                slug: "fix-auth".to_string(),
                prd_path: PathBuf::from("/workspace/prd/fix-auth.md"),
                failure_context: "T3 gate failed: clippy warnings".to_string(),
            },
            workdir: PathBuf::from("/workspace"),
            adapter_key: adapter_keys::PRD_REPLAN.to_string(),
            overrides: PlanGeneratorOverrides {
                model: Some("claude-opus-4-6".to_string()),
                role: Some("strategist".to_string()),
                allowed_tools: Some("read,write,bash".to_string()),
                template: Some("standard".to_string()),
                budget_usd: Some(5.0),
                repair_cap: Some(4),
            },
            dry_run: true,
        };
        let json = serde_json::to_string_pretty(&request).unwrap();
        let roundtrip: PlanGeneratorRequest = serde_json::from_str(&json).unwrap();

        assert_eq!(roundtrip.adapter_key, adapter_keys::PRD_REPLAN);
        assert!(roundtrip.dry_run);
        assert_eq!(
            roundtrip.overrides.model.as_deref(),
            Some("claude-opus-4-6")
        );
        assert_eq!(roundtrip.overrides.repair_cap, Some(4));
        assert_eq!(roundtrip.overrides.budget_usd, Some(5.0));
        assert!(roundtrip.source.has_failure_context());
        assert_eq!(
            roundtrip.source.failure_context(),
            Some("T3 gate failed: clippy warnings")
        );
    }

    // ---- Dry-run flag ----

    #[test]
    fn dry_run_request_does_not_persist() {
        let request = PlanGeneratorRequest {
            source: PlanSource::Prompt {
                prompt: "test".to_string(),
            },
            workdir: PathBuf::from("/tmp"),
            adapter_key: adapter_keys::PLAN_GENERATE.to_string(),
            overrides: PlanGeneratorOverrides::default(),
            dry_run: true,
        };
        assert!(request.dry_run);
    }

    // ---- Each adapter key maps to expected PlanSource variant ----

    #[test]
    fn plan_source_adapter_key_mapping() {
        let prd_keys = [
            adapter_keys::PRD_DEFAULT,
            adapter_keys::PRD_MODEL,
            adapter_keys::DO_COMPLEX,
            adapter_keys::CLI_SERVE_RUNTIME,
            adapter_keys::SERVE_RUNTIME,
            adapter_keys::SERVE_HTTP,
        ];
        let prompt_keys = [adapter_keys::DO_STANDARD, adapter_keys::PLAN_GENERATE];
        let replan_keys = [adapter_keys::PRD_REPLAN, adapter_keys::GATE_REPLAN];

        // All keys are in exactly one category.
        let total = prd_keys.len() + prompt_keys.len() + replan_keys.len();
        assert_eq!(total, 10, "all 10 adapter keys must be categorized");

        // No overlap.
        let mut all = std::collections::HashSet::new();
        for k in prd_keys
            .iter()
            .chain(prompt_keys.iter())
            .chain(replan_keys.iter())
        {
            assert!(all.insert(*k), "duplicate key: {k}");
        }
    }
}
