#!/usr/bin/env python3
"""Work-graph tool: create, check, close, sync and render work/items (replaced later by `roko work`).

Usage:
  work.py id --kind gap --title "…" --created 2026-09-28 --source "…"   # print a hash ID
  work.py new --kind gap --title "…" --source "…" [--root work|local] [--subsystem a,b] [--severity p2] [--triage verified]
  work.py check [--strict]                                               # validate both roots (+ verify-command lint)
  work.py render                                                         # regenerate views, including DRIFT.md
  work.py park <id>… --reason "…"                                        # not planned: move to parked/
  work.py unpark <id>…                                                   # restore status, move back to items/

Picking up work (work/README.md, "For agents"):
  work.py next [--n 4] [--goal G] [--max-size M] [--json]   # top unclaimed items that don't touch the same files
  work.py claim <id>… --by "<who>" [--branch B] [--worktree PATH] [--session S]   # shared claim in the main tree's .roko/work-claims/
        [--executor claude-agent|claude-session|roko-plan|human] [--via work-batch|work-next|manual|roko-plan] [--size S|M|L]
  work.py release <id>… [--session S] [--reason verify-fail|blocked|decision-needed|conflict|timeout|session-limit]
  work.py claims                             # list live and stale claims

The development record (work/telemetry/README.md; not for workers): claim and release, run in the main checkout, append
an event to work/telemetry/events/<session>.jsonl (session: --session, else $WORK_SESSION, else --by). The orchestrator
logs what happens after the work:
  work.py event merged|post-verify|escape|intervention <id> [--merge-sha REV] [--conflicts N] [--fixups N] [--rc N] [--caused-by ID]

Keeping the graph current (work/README.md, "Keeping the graph current"):
  work.py close <id> --evidence "…" [--commit REV] [--run-id RUN] [--status done|wontfix|superseded] [--duplicate-of ID]
        [--model M] [--assist EXECUTOR]   # [closed] also gets the claim's executor, via, size and claimed_at
  work.py sync [--dry-run]                   # close items from `Closes: <id>` commit trailers and passed plan tasks with closes=[…]
  work.py drift [--json]                     # open items whose evidence may be out of date
  work.py touched [--rev REV|A..B]           # open items a commit (or range) touched or mentioned
  work.py verify [<id>…] [--closed-since DATE] [--static-only]   # run [[verify]] commands
  work.py apply-verdicts --snapshot drift.json <verdicts.jsonl>… [--dry-run]   # apply a sweep's agent verdicts
  work.py hook                               # Claude Code PostToolUse adapter (reads the hook payload on stdin)
"""
from __future__ import annotations

import argparse, datetime as dt, hashlib, json, os, re, subprocess, sys, time, tomllib
from collections import Counter, defaultdict
from pathlib import Path

REPO = Path(os.environ.get("WORK_REPO") or Path(__file__).resolve().parents[1])
ROOTS = {"work": REPO / "work", "local": REPO / ".roko" / "work-local"}
PREFIX = {"gap": "gap", "bug": "bug", "regression": "reg", "finding": "find", "decision": "dec", "spec": "spec", "question": "q"}
STATUSES = {"open", "in_progress", "blocked", "done", "wontfix", "superseded", "parked"}
OPEN = {"open", "in_progress", "blocked"}
TRIAGE = {"verified", "unverified"}
SEV = ["p0", "p1", "p2", "p3"]
REQUIRED = ["id", "kind", "title", "status", "triage", "severity", "subsystem", "created", "source"]
ID_RE = re.compile(r"^(gap|bug|reg|find|dec|spec|q)-[0-9a-f]{6,8}$")
ID_ANY = re.compile(r"\b(?:gap|bug|reg|find|dec|spec|q)-[0-9a-f]{6,8}\b")
# GitHub-style closing keywords followed by one or more item IDs: "Closes: bug-1a2b3c, gap-4d5e6f"
CLOSE_RE = re.compile(r"\b(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\b:?\s+((?:(?:gap|bug|reg|find|dec|spec|q)-[0-9a-f]{6,8}(?:\s*(?:,|and)\s*)?)+)", re.I)
GEN_NOTE = "<!-- GENERATED by work tooling from work/items — do not edit by hand -->"
GOALS_FILE = ROOTS["work"] / "goals.toml"
STALE_DAYS = 21
HEAVY = re.compile(r"^\s*(?:\(?\s*cd [^&]*&&\s*)?(?:cargo|npx|npm|pnpm|node|roko|target/|\./target|curl|gh )")


def set_repo(path) -> None:
    """Point the tool at another checkout (tests; the hook acts on the checkout a commit happened in)."""
    global REPO, ROOTS, GOALS_FILE
    REPO = Path(path).resolve()
    ROOTS = {"work": REPO / "work", "local": REPO / ".roko" / "work-local"}
    GOALS_FILE = ROOTS["work"] / "goals.toml"


def load_goals():
    return tomllib.loads(GOALS_FILE.read_text()).get("goal", []) if GOALS_FILE.exists() else []


def make_id(kind: str, title: str, created: str, source: str, n: int = 6) -> str:
    h = hashlib.sha256(f"{kind}|{title}|{created}|{source}".encode()).hexdigest()
    return f"{PREFIX[kind]}-{h[:n]}"


def slug(title: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return "-".join(s.split("-")[:7])[:60] or "item"


def parse(path: Path):
    text = path.read_text()
    m = re.match(r"\+\+\+\n(.*?)\n\+\+\+\n?(.*)", text, re.S)
    if not m:
        raise ValueError("missing +++ TOML front matter")
    meta = tomllib.loads(m.group(1))
    return meta, m.group(2)


def load(root_key: str):
    items, errors = [], []
    for sub in ("items", "parked"):
        d = ROOTS[root_key] / sub
        if not d.exists():
            continue
        for p in sorted(d.glob("*.md")):
            if p.name.startswith("_"):
                continue
            try:
                meta, body = parse(p)
            except Exception as e:  # noqa: BLE001
                errors.append(f"{p.relative_to(REPO)}: {e}")
                continue
            meta["_path"] = p
            meta["_body"] = body
            meta["_root"] = root_key
            meta["_dir"] = sub
            items.append(meta)
    return items, errors


def validate(items):
    errs, seen = [], {}
    goal_keys = {g["key"] for g in load_goals()}
    for it in items:
        if "goal" in it and it["goal"] not in goal_keys:
            errs.append(f"{it['_path'].relative_to(REPO)}: goal {it['goal']!r} is not in work/goals.toml")
        if "hold" in it and not (isinstance(it["hold"], str) and it["hold"].strip()):
            errs.append(f"{it['_path'].relative_to(REPO)}: hold must be a non-empty reason string")
        if "size" in it and it["size"] not in SIZES:
            errs.append(f"{it['_path'].relative_to(REPO)}: size must be one of {SIZES}")
        if "rank" in it and not isinstance(it["rank"], int):
            errs.append(f"{it['_path'].relative_to(REPO)}: rank must be an integer")
        p = it["_path"].relative_to(REPO)
        for k in REQUIRED:
            if k not in it or it[k] in ("", None):
                errs.append(f"{p}: missing {k}")
        if not ID_RE.match(str(it.get("id", ""))):
            errs.append(f"{p}: bad id {it.get('id')!r}")
        elif not it["_path"].name.startswith(it["id"] + "-"):
            errs.append(f"{p}: file name must start with id {it['id']}-")
        if it.get("id") in seen:
            errs.append(f"{p}: duplicate id {it['id']} (also {seen[it['id']]})")
        seen[it.get("id")] = p
        if it.get("kind") not in PREFIX:
            errs.append(f"{p}: bad kind {it.get('kind')!r}")
        elif ID_RE.match(str(it.get("id", ""))) and not it["id"].startswith(PREFIX[it["kind"]] + "-"):
            errs.append(f"{p}: id prefix does not match kind {it['kind']}")
        if it.get("status") not in STATUSES:
            errs.append(f"{p}: bad status {it.get('status')!r}")
        if it.get("triage") not in TRIAGE:
            errs.append(f"{p}: bad triage {it.get('triage')!r}")
        if it.get("severity") not in SEV:
            errs.append(f"{p}: bad severity {it.get('severity')!r}")
        if not isinstance(it.get("subsystem"), list) or not it.get("subsystem"):
            errs.append(f"{p}: subsystem must be a non-empty list")
        if it.get("status") == "done":
            closed = it.get("closed") or {}
            if not (closed.get("evidence") or closed.get("run_id") or closed.get("commit")):
                errs.append(f"{p}: status=done needs [closed] evidence/run_id/commit")
        if it.get("status") in ("wontfix", "superseded") and not (it.get("closed") or {}).get("evidence"):
            errs.append(f"{p}: status={it.get('status')} needs [closed].evidence")
        errs += [f"{p}: {e}" for e in check_closed(it.get("closed") or {})]
        if it.get("triage") == "verified" and not it.get("last_verified"):
            errs.append(f"{p}: triage=verified needs last_verified")
        if (it.get("status") == "parked") != (it.get("_dir") == "parked"):
            errs.append(f"{p}: parked items live in parked/, all other items in items/")
        if it.get("status") == "parked" and not ((it.get("parked") or {}).get("at") and (it.get("parked") or {}).get("reason")):
            errs.append(f"{p}: status=parked needs [parked] at and reason")
    ids = {it.get("id") for it in items}
    for it in items:
        links = it.get("links") or {}
        for key in ("depends_on", "blocks", "supersedes"):
            for ref in links.get(key, []) or []:
                if ID_RE.match(ref) and ref not in ids:
                    errs.append(f"{it['_path'].relative_to(REPO)}: links.{key} → unknown {ref}")
    return errs


# ---------------------------------------------------------------- verify commands

def split_and(cmd: str) -> list[str]:
    """Split a shell command on top-level `&&` (outside quotes and parentheses)."""
    parts, cur, q, depth, i = [], "", None, 0, 0
    while i < len(cmd):
        c = cmd[i]
        if q:
            cur += c
            if c == q:
                q = None
        elif c in "'\"":
            q = c
            cur += c
        elif c == "(":
            depth += 1
            cur += c
        elif c == ")":
            depth -= 1
            cur += c
        elif cmd.startswith("&&", i) and depth == 0:
            parts.append(cur.strip())
            cur, i = "", i + 2
            continue
        else:
            cur += c
        i += 1
    parts.append(cur.strip())
    return [p for p in parts if p]


def static_prefix(cmd: str) -> str:
    """The part of a verify command before its first cargo/npm/network step: cheap to run at any time."""
    out = []
    for part in split_and(cmd):
        if HEAVY.match(part) or re.match(r"^\(?\s*cd\s", part):
            break
        out.append(part)
    return " && ".join(out)


def run_shell(cmd: str, timeout: int = 120) -> int:
    try:
        return subprocess.run(cmd, shell=True, cwd=REPO, capture_output=True, text=True, timeout=timeout).returncode
    except subprocess.TimeoutExpired:
        return 124


def static_verify_state(it) -> str:
    """'green' if every verify command's static prefix passes, 'red' if any fails, 'none' if there is nothing static."""
    prefixes = [static_prefix(v.get("command", "")) for v in it.get("verify") or []]
    prefixes = [p for p in prefixes if p]
    if not prefixes:
        return "none"
    return "green" if all(run_shell(p, 60) == 0 for p in prefixes) else "red"


def _test_filter_exists(crate: str, filt: str) -> bool:
    """True if a cargo test filter names an existing test fn or module in the crate."""
    name = filt.split("::")[-1]
    where = ["--", f"crates/{crate}/"]
    return (git_ok("grep", "-q", "-w", f"fn {name}", *where) or git_ok("grep", "-q", "-w", f"mod {name}", *where)
            or bool(git("ls-files", f"crates/{crate}/**/{name}.rs", f"crates/{crate}/tests/{name}.rs").strip()))


def lint_verify(cmd: str) -> list[str]:
    """Patterns that make a verify command pass while the problem still exists."""
    warns = []
    for part in split_and(cmd):
        if re.search(r"\|\s*head\b", part) and not re.search(r"\|\s*grep -q", part.split("| head")[-1]):
            warns.append("pipes into `head`, so it exits 0 whatever grep finds")
        m = re.match(r"^cargo test -p (\S+)(.*)$", part)
        if m:
            args = m.group(2).split()
            target = any(a in ("--test", "--bin", "--example") for a in args)
            takes_value = {"--test", "--bin", "--example", "--bench", "--features", "--test-threads", "--skip", "-F"}
            filters, skip = [], False
            for x in args:
                if skip:
                    skip = False
                    continue
                if x in takes_value:
                    skip = True
                elif not x.startswith("-"):
                    filters.append(x)
            guarded = re.search(r"grep\b[^&]*\bfn |test -f ", cmd)
            if not filters and not target:
                warns.append(f"runs the whole `{m.group(1)}` test suite, which passes while the bug is present")
            elif filters and not guarded and not _test_filter_exists(m.group(1), filters[-1]):
                warns.append(f"names test `{filters[-1]}`, which does not exist yet, and a cargo test filter that matches no test "
                             "exits 0; guard it with `grep -rqw 'fn <test>' crates/<crate>/ &&`")
    return warns


# ---------------------------------------------------------------- git + drift

def git(*args: str) -> str:
    p = subprocess.run(["git", *args], cwd=REPO, capture_output=True, text=True)
    return p.stdout if p.returncode == 0 else ""


def git_ok(*args: str) -> bool:
    return subprocess.run(["git", *args], cwd=REPO, capture_output=True, text=True).returncode == 0


def head_rev() -> str:
    return git("rev-parse", "--short=9", "HEAD").strip()


def anchor_parts(a: str):
    """'path::symbol', 'path:line' or 'path' → (path, symbol); (None, None) for non-path anchors."""
    a = a.strip()
    m = re.match(r"^([A-Za-z0-9_.@/\-]+?)(?:::(.+)|:(\d+(?:-\d+)?))?$", a)
    if not m:
        return None, None
    path = m.group(1)
    if "/" not in path and not (REPO / path).exists():
        return None, None
    sym = m.group(2).split("::")[-1].split("(")[0].strip() if m.group(2) else None
    return path.rstrip("/") if path.endswith("/") else path, sym


def commit_log(since: str | None = None, names: bool = True):
    """[(sha, date, subject, body, [files])] newest first; one pass over git log (merges excluded: their
    commits appear individually)."""
    args = ["log", "--no-merges", "--date=short", "--format=%x1e%h%x1f%cd%x1f%s%x1f%b%x1f"] + (["--name-only"] if names else [])
    if since:
        args.append(f"--since={since}")
    out = []
    for rec in git(*args).split("\x1e")[1:]:
        f = rec.split("\x1f")
        if len(f) < 5:
            continue
        files = [x for x in f[4].splitlines() if x.strip()]
        out.append((f[0], f[1], f[2], f[3], files))
    return out


def _item_since(it) -> str:
    return str(it.get("last_verified") or it.get("created") or "1970-01-01")


def plan_closes():
    """{item id: [(plan path, task id, verdict or None, run_id or None)]} from plans/**/tasks.toml + Graph checkpoints."""
    out = defaultdict(list)
    plans = REPO / "plans"
    if not plans.exists():
        return out
    for tf in plans.rglob("tasks.toml"):
        if any(part.startswith(".") or part == "node_modules" for part in tf.parts):
            continue
        try:
            data = tomllib.loads(tf.read_text())
        except Exception:  # noqa: BLE001
            continue
        tasks = data.get("task") or data.get("tasks") or []
        if not any(t.get("closes") for t in tasks if isinstance(t, dict)):
            continue
        plan_id = (data.get("meta") or {}).get("plan") or tf.parent.name
        cp_file = REPO / ".roko" / "state" / "graph" / plan_id / "checkpoint.json"
        verdicts, run_id = {}, None
        if cp_file.exists():
            try:
                cp = json.loads(cp_file.read_text())
                run_id = cp.get("run_id")
                verdicts = ((cp.get("extensions") or {}).get("roko.gate.verdict@1") or {}).get("value", {}).get("verdicts", {})
            except Exception:  # noqa: BLE001
                pass
        for t in tasks:
            if not isinstance(t, dict):
                continue
            for iid in t.get("closes") or []:
                out[iid].append((str(tf.parent.relative_to(REPO)), t.get("id"), verdicts.get(t.get("id")), run_id))
    return out


def compute_drift(items, stale_days: int = STALE_DAYS, today: dt.date | None = None):
    """Per open item: why its recorded state may be out of date. Git and file reads only; runs no commands."""
    today = today or dt.date.today()
    opened = [i for i in items if i.get("status") in OPEN]
    if not opened:
        return {}
    horizon = min(str(i.get("created") or "1970-01-01") for i in opened)
    log = commit_log(since=horizon)
    by_file = defaultdict(list)
    for c in log:
        for f in c[4]:
            by_file[f].append(c)
    rev_sets = {}
    closes = plan_closes()
    text_cache = {}
    patch_cache = {}

    def patch_mentions(sha, path, symbols):
        """Does commit `sha`'s diff of `path` change a line (or hunk) that names one of `symbols`?"""
        if (sha, path) not in patch_cache:
            patch_cache[(sha, path)] = git("show", "--format=", "-U3", sha, "--", path)
        changed = [ln for ln in patch_cache[(sha, path)].splitlines()
                   if (ln[:1] in "+-" and not ln.startswith(("+++", "---"))) or ln.startswith("@@")]
        return any(re.search(r"\b" + re.escape(sym) + r"\b", ln) for ln in changed for sym in symbols)

    out = {}
    for it in opened:
        since = _item_since(it)
        rev = it.get("last_verified_rev")
        if rev and rev not in rev_sets:
            ok = git_ok("merge-base", "--is-ancestor", rev, "HEAD")
            rev_sets[rev] = {s[:7] for s in git("rev-list", f"{rev}..HEAD").split()} if ok else None

        def after_check(c):
            s = rev_sets.get(rev) if rev else None
            return (c[0][:7] in s) if s is not None else c[1] > since

        d = {"gone": [], "touched": [], "claimed": [], "mentioned": [], "plan_passed": [], "plan_other": [], "stale": False}
        # Per file: the symbols the item names there. A file anchored only by path or line is watched as a whole;
        # a file anchored by symbol counts as changed only when a commit's diff touches one of those symbols.
        symbols, whole = defaultdict(set), set()
        for a in it.get("anchors") or []:
            path, sym = anchor_parts(a)
            if path:
                (symbols[path].add(sym) if sym else whole.add(path))
        own = str(it["_path"].relative_to(REPO))
        for a in it.get("anchors") or []:
            path, sym = anchor_parts(a)
            if not path:
                continue
            p = REPO / path
            if not p.exists():
                d["gone"].append(a)
                continue
            if sym and p.is_file():
                if path not in text_cache:
                    try:
                        text_cache[path] = p.read_text(errors="replace")
                    except Exception:  # noqa: BLE001
                        text_cache[path] = ""
                if not re.search(r"\b" + re.escape(sym) + r"\b", text_cache[path]):
                    d["gone"].append(a)
            hits = by_file.get(path, []) if p.is_file() else [c for f, cs in by_file.items() if f.startswith(path + "/") for c in cs]
            for c in hits:
                if not after_check(c) or own in c[4] or (c[0], c[2]) in {(t[0], t[2]) for t in d["touched"]}:
                    continue
                if path not in whole and symbols.get(path) and not patch_mentions(c[0], path, symbols[path]):
                    continue
                d["touched"].append((c[0], c[1], c[2], path))
        created = str(it.get("created") or "1970-01-01")
        for c in log:
            msg = c[2] + "\n" + c[3]
            if it["id"] not in msg:
                continue
            closing = any(it["id"] in m.group(1) for m in CLOSE_RE.finditer(msg))
            if closing and c[1] >= created:
                d["claimed"].append((c[0], c[1], c[2]))
            elif after_check(c) and own not in c[4]:  # a commit that also edits the item already accounted for it
                d["mentioned"].append((c[0], c[1], c[2]))
        for plan, task, verdict, run_id in closes.get(it["id"], []):
            (d["plan_passed"] if verdict == "passed" else d["plan_other"]).append((plan, task, verdict, run_id))
        try:
            d["stale"] = (today - dt.date.fromisoformat(since)).days > stale_days
        except ValueError:
            d["stale"] = True
        d["touched"].sort(key=lambda t: t[1], reverse=True)
        if d["gone"] or d["touched"] or d["claimed"] or d["mentioned"] or d["plan_passed"] or d["stale"]:
            out[it["id"]] = d
    return out


def render_drift(root: Path, items, drift, head: str) -> list[str]:
    by_id = {i["id"]: i for i in items}
    link = lambda it: f"[{it['id']}]({it['_path'].relative_to(root)})"  # noqa: E731
    groups = {"likely": [], "gone": [], "touched": [], "mentioned": [], "stale": []}
    for iid, d in drift.items():
        if d["claimed"] or d["plan_passed"]:
            groups["likely"].append(iid)
        elif d["gone"]:
            groups["gone"].append(iid)
        elif d["touched"]:
            groups["touched"].append(iid)
        elif d["mentioned"]:
            groups["mentioned"].append(iid)
        elif d["stale"]:
            groups["stale"].append(iid)
    key = lambda iid: sev_key(by_id[iid])  # noqa: E731
    out = ["# Drift: open items to re-check", "", GEN_NOTE, "",
           f"At HEAD `{head}`: open items whose recorded state may be out of date. Re-check each one against the code, "
           "then close it (`tools/work.py close`) or refresh `last_verified`. `tools/work.py sync` closes the \"likely done\" "
           "ones whose closure is declared by a commit trailer or a passed plan task. Procedure: `work/README.md`, "
           "\"Keeping the graph current\".", ""]
    titles = [("likely", "Likely done: a commit or a passed plan task says it closes them"),
              ("gone", "Anchor gone: the code it points at no longer exists"),
              ("touched", "Code changed since the last check"),
              ("mentioned", "Mentioned in a commit since the last check"),
              ("stale", f"Not checked for more than {STALE_DAYS} days")]
    for g, title in titles:
        ids = sorted(groups[g], key=key)
        out += [f"## {title} ({len(ids)})", ""]
        for iid in ids:
            it, d = by_id[iid], drift[iid]
            why = []
            why += [f"{c[0]} says it closes it" for c in d["claimed"][:2]]
            why += [f"plan task `{p}#{t}` passed" for p, t, _, _ in d["plan_passed"][:2]]
            why += [f"`{a}` not found" for a in d["gone"][:2]]
            if d["touched"] and g in ("touched", "gone", "likely"):
                shas = []
                for t in d["touched"]:
                    if t[0] not in shas:
                        shas.append(t[0])
                why.append(f"{len(shas)} commit(s) touched its anchors since {it.get('last_verified_rev') or it.get('last_verified')}"
                           f" (latest {d['touched'][0][0]} {d['touched'][0][2][:60]!r})")
            if d["mentioned"] and g == "mentioned":
                why.append(f"mentioned in {', '.join(c[0] for c in d['mentioned'][:3])}")
            if g == "stale":
                why.append(f"last checked {it.get('last_verified') or 'never'}")
            out.append(f"- **{it['severity'].upper()}** {link(it)} {it['title']} — {'; '.join(why)}")
        out += ["- none", ""] if not ids else [""]
    return out


def drift_summary(drift) -> str:
    c = Counter()
    for d in drift.values():
        if d["claimed"] or d["plan_passed"]:
            c["likely done"] += 1
        elif d["gone"]:
            c["anchor gone"] += 1
        elif d["touched"]:
            c["changed since checked"] += 1
        elif d["mentioned"]:
            c["mentioned in commits"] += 1
        elif d["stale"]:
            c["stale"] += 1
    order = ["likely done", "anchor gone", "changed since checked", "mentioned in commits", "stale"]
    return " · ".join(f"{c[k]} {k}" for k in order if c[k])


# ---------------------------------------------------------------- claims + picking work

CLAIM_TTL_HOURS = 24
SIZES = ["S", "M", "L"]


def main_root() -> Path:
    """The main worktree (claims are shared by every worktree of the repo, so they live there)."""
    common = subprocess.run(["git", "rev-parse", "--path-format=absolute", "--git-common-dir"], cwd=REPO,
                            capture_output=True, text=True).stdout.strip()
    return Path(common).parent if common else REPO


def claims_dir() -> Path:
    return main_root() / ".roko" / "work-claims"


def load_claims(ttl_hours: int = CLAIM_TTL_HOURS):
    """{id: claim dict with 'age_h' and 'stale'} from .roko/work-claims/*.json."""
    out = {}
    d = claims_dir()
    for f in sorted(d.glob("*.json")) if d.exists() else []:
        try:
            c = json.loads(f.read_text())
            age = (time.time() - dt.datetime.fromisoformat(c["at"]).timestamp()) / 3600
        except Exception:  # noqa: BLE001
            continue
        c["age_h"] = round(age, 1)
        c["stale"] = age > ttl_hours
        out[c["id"]] = c
    return out


def prune_claims():
    """Drop claims whose item is no longer open in the main checkout (it was merged closed, or parked)."""
    d = claims_dir()
    if not d.exists():
        return []
    main = main_root()
    gone = []
    for f in d.glob("*.json"):
        iid = f.stem
        hits = [p for sub in ("work/items", "work/parked", ".roko/work-local/items") for p in (main / sub).glob(f"{iid}-*.md")]
        try:
            status = tomllib.loads(re.match(r"\+\+\+\n(.*?)\n\+\+\+", hits[0].read_text(), re.S).group(1)).get("status") if hits else None
        except Exception:  # noqa: BLE001
            continue
        if status not in OPEN:
            f.unlink()
            gone.append(iid)
    return gone


def footprint(it) -> set[str]:
    """Files (or directories) an item's anchors point at: two items with overlapping footprints conflict."""
    return {p for p, _ in (anchor_parts(a) for a in it.get("anchors") or []) if p}


def overlaps(a: set[str], b: set[str]) -> bool:
    return any(x == y or x.startswith(y + "/") or y.startswith(x + "/") for x in a for y in b)


def goal_order():
    return {g["key"]: n for n, g in enumerate(load_goals())}


def pick_key(it, order):
    return (order.get(it.get("goal"), len(order)),) + now_key(it)


def pick_next(items, n: int = 1, goal: str | None = None, max_size: str | None = None, claims=None):
    """Top-priority open items that a worker can start now, pairwise free of file conflicts.

    Skips: claimed items (live claims), items on hold, unverified items, decisions/questions (they need a human), items whose
    depends_on are still open, items larger than max_size, and items whose footprint overlaps a claimed item or an
    item already picked. Returns (picked, skipped_reasons)."""
    claims = load_claims() if claims is None else claims
    live = {k: c for k, c in claims.items() if not c["stale"]}
    by_id = {i["id"]: i for i in items}
    busy = set().union(*(footprint(by_id[k]) for k in live if k in by_id)) if live else set()
    order = goal_order()
    cands = [i for i in items if i.get("status") == "open" and i.get("triage") == "verified" and not i.get("hold")
             and i.get("kind") not in ("decision", "question") and i["id"] not in live
             and (goal is None or i.get("goal") == goal)]
    picked, skipped = [], Counter()
    for it in sorted(cands, key=lambda i: pick_key(i, order)):
        if len(picked) >= n:
            break
        deps = [d for d in (it.get("links") or {}).get("depends_on", []) or [] if by_id.get(d, {}).get("status") in OPEN]
        if deps:
            skipped["waits on an open dependency"] += 1
            continue
        if max_size and it.get("size") in SIZES and SIZES.index(it["size"]) > SIZES.index(max_size):
            skipped[f"larger than {max_size}"] += 1
            continue
        fp = footprint(it)
        if fp and overlaps(fp, busy):
            skipped["touches files of a claimed or already-picked item"] += 1
            continue
        picked.append(it)
        busy |= fp
    return picked, skipped


def cmd_next(a):
    prune_claims()
    items = [i for i in load("work")[0]]
    picked, skipped = pick_next(items, a.n, a.goal, a.max_size)
    order = goal_order()
    if a.json:
        rows = [{"id": i["id"], "title": i["title"], "goal": i.get("goal"), "severity": i["severity"], "size": i.get("size"),
                 "path": str(i["_path"].relative_to(REPO)), "anchors": i.get("anchors") or [],
                 "verify": [v.get("command") for v in i.get("verify") or []]} for i in picked]
        json.dump(rows, sys.stdout, indent=1)
        print()
        return
    goals = {g["key"]: g["title"] for g in load_goals()}
    for i in picked:
        fp = footprint(i)
        print(f"{i['id']}  [{i['severity']}{'/' + i['size'] if i.get('size') else ''}] {i['title']}")
        print(f"    goal: {goals.get(i.get('goal'), 'later (no goal)')} · file: {i['_path'].relative_to(REPO)}"
              + ("" if fp else " · footprint unknown (no path anchors): check for conflicts by hand"))
    if not picked:
        print("nothing available")
    if skipped:
        print("skipped: " + ", ".join(f"{v} {k}" for k, v in skipped.items()))


def cmd_claim(a):
    idx = index()
    d = claims_dir()
    d.mkdir(parents=True, exist_ok=True)
    live = {k for k, c in load_claims().items() if not c["stale"]}
    session = session_name(a.session, a.by)
    for iid in a.ids:
        it = idx.get(iid)
        if it is None or it.get("status") not in OPEN:
            sys.exit(f"{iid}: not found or not open")
        if iid in live and not a.force:
            c = load_claims()[iid]
            sys.exit(f"{iid}: already claimed by {c.get('by')} {c['age_h']}h ago (use --force to take over a claim you know is dead)")
        now = dt.datetime.now().astimezone()
        size = a.size or it.get("size")
        rec = {"id": iid, "by": a.by, "at": now.isoformat(timespec="seconds"), "claimed_at": utc_ts(now),
               "branch": a.branch, "worktree": a.worktree, "title": it["title"], "session": session,
               "executor": a.executor, "via": a.via, "size": size}
        f = d / f"{iid}.json"
        try:
            fd = os.open(f, os.O_WRONLY | os.O_CREAT | (0 if a.force else os.O_EXCL), 0o644)
        except FileExistsError:
            sys.exit(f"{iid}: claimed by someone else a moment ago")
        with os.fdopen(fd, "w") as fh:
            fh.write(json.dumps(rec, indent=1) + "\n")
        log_event("claim", iid, session=session, executor=a.executor, via=a.via, branch=a.branch, by=a.by,
                  size=size, claimed_at=rec["claimed_at"], force=True if a.force else None)
        print(f"claimed {iid} for {a.by}")


def cmd_release(a):
    claims = load_claims()
    for iid in a.ids:
        f = claims_dir() / f"{iid}.json"
        if f.exists():
            c = claims.get(iid) or {}
            # Logged before the claim goes: the event keeps what the claim knew.
            log_event("release", iid, session=session_name(a.session, c.get("session"), c.get("by")),
                      executor=c.get("executor"), via=c.get("via"), branch=c.get("branch"), by=c.get("by"),
                      reason=a.reason, size=c.get("size"), claimed_at=c.get("claimed_at"))
            f.unlink()
            print(f"released {iid}")
        else:
            print(f"{iid}: no claim")


def cmd_claims(a):
    for iid in prune_claims():
        print(f"pruned {iid} (closed)")
    claims = load_claims()
    if not claims:
        print("no claims")
    for iid, c in sorted(claims.items(), key=lambda kv: kv[1]["at"]):
        where = " · ".join(x for x in (c.get("branch"), c.get("worktree")) if x)
        print(f"{'STALE ' if c['stale'] else ''}{iid} by {c.get('by')} {c['age_h']}h ago{(' · ' + where) if where else ''} — {c.get('title', '')}")


# ---------------------------------------------------------------- event log (work/telemetry/; not for workers)
#
# One append-only file per session, work/telemetry/events/<session>.jsonl in the main checkout, one
# roko.work_event/1 object per line. Only that session writes its file, so sessions never conflict. A worker in a
# linked worktree logs nothing (W12: workers never write events or see metrics), and no view reads the log.

EVENT_SCHEMA = "roko.work_event/1"
EVENTS = ("claim", "release", "closed", "merged", "post-verify", "escape", "intervention", "lane-start")
EVENT_SOURCES = ("live", "harvest", "reconciled", "backfill")
EVENT_FIELDS = ("schema", "ts", "event", "item", "executor", "via", "session", "branch", "concurrency", "source")
EXECUTORS = ("claude-agent", "claude-session", "roko-plan", "human")
VIAS = ("work-batch", "work-next", "manual", "roko-plan")
RELEASE_REASONS = ("verify-fail", "blocked", "decision-needed", "conflict", "timeout", "session-limit")
# Closures that sync reconciles from a commit with no claim have no known executor; a backfilled sweep or triage
# closure checked an item rather than implementing it.
CLOSED_EXECUTORS = EXECUTORS + ("unknown", "verification-only")
TS_RE = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$")


def utc_ts(when: dt.datetime | None = None) -> str:
    """An ISO 8601 UTC timestamp to the second, such as 2026-09-30T08:15:00Z."""
    when = when or dt.datetime.now(dt.timezone.utc)
    return when.astimezone(dt.timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


def events_dir() -> Path:
    return main_root() / "work" / "telemetry" / "events"


def in_main_checkout() -> bool:
    return REPO.resolve() == main_root().resolve()


def session_name(explicit=None, *fallbacks) -> str:
    """The session a command logs under: --session, else $WORK_SESSION, else the first fallback given (such as
    --by), as a slug. It names the session's events file."""
    raw = explicit or os.environ.get("WORK_SESSION") or next((f for f in fallbacks if f), None) or "unnamed"
    return re.sub(r"[^a-z0-9]+", "-", str(raw).lower()).strip("-")[:60] or "unnamed"


def event_row(event: str, item, *, session: str, ts=None, executor=None, via=None, branch=None, concurrency=None,
              source="live", **fields) -> dict:
    """One roko.work_event/1 row: the common fields, always present (null when unknown), then the event's own."""
    row = {"schema": EVENT_SCHEMA, "ts": ts or utc_ts(), "event": event, "item": item, "executor": executor,
           "via": via, "session": session, "branch": branch, "concurrency": concurrency, "source": source}
    row.update({k: v for k, v in fields.items() if v is not None})
    return row


def check_event(row) -> list[str]:
    """Why `row` is not a valid roko.work_event/1 event; empty when it is."""
    errs = [f"missing {k}" for k in EVENT_FIELDS if k not in row]
    if row.get("schema") != EVENT_SCHEMA:
        errs.append(f"schema is not {EVENT_SCHEMA}")
    if row.get("event") not in EVENTS:
        errs.append(f"unknown event {row.get('event')!r}")
    if row.get("source") not in EVENT_SOURCES:
        errs.append(f"unknown source {row.get('source')!r}")
    if not TS_RE.match(str(row.get("ts"))):
        errs.append(f"ts {row.get('ts')!r} is not a UTC timestamp")
    if row.get("item") is not None and not ID_RE.match(str(row["item"])):
        errs.append(f"bad item {row.get('item')!r}")
    if row.get("item") is None and row.get("event") != "lane-start":
        errs.append("no item")
    if not (isinstance(row.get("session"), str) and row["session"]):
        errs.append("no session")
    c = row.get("concurrency")
    if c is not None and not (isinstance(c, int) and not isinstance(c, bool) and c >= 0):
        errs.append(f"bad concurrency {c!r}")
    return errs


def log_event(event: str, item, **kw) -> dict | None:
    """Append one event to the session's file in the main checkout. Records how many claims are live as
    `concurrency`. Returns the row, or None in a linked worktree, where nothing is logged."""
    if not in_main_checkout():
        return None
    live = sum(1 for c in load_claims().values() if not c["stale"])
    row = event_row(event, item, concurrency=live, **kw)
    d = events_dir()
    d.mkdir(parents=True, exist_ok=True)
    with open(d / f"{row['session']}.jsonl", "a") as fh:
        fh.write(json.dumps(row) + "\n")
    return row


def item_claim(iid: str) -> dict:
    """The claim on `iid` in the main checkout's claims directory, live or stale; {} when there is none."""
    try:
        return json.loads((claims_dir() / f"{iid}.json").read_text())
    except Exception:  # noqa: BLE001
        return {}


def check_closed(closed: dict) -> list[str]:
    """Why a [closed] block's executor fields (gap-0b9056) are malformed; every one of them is optional."""
    errs = []
    if closed.get("executor") is not None and closed["executor"] not in CLOSED_EXECUTORS:
        errs.append(f"[closed].executor must be one of {CLOSED_EXECUTORS}")
    if closed.get("via") is not None and closed["via"] not in VIAS:
        errs.append(f"[closed].via must be one of {VIAS}")
    if closed.get("size") is not None and closed["size"] not in SIZES:
        errs.append(f"[closed].size must be one of {SIZES}")
    if closed.get("forced") is not None and not isinstance(closed["forced"], bool):
        errs.append("[closed].forced must be true or false")
    for k in ("at_ts", "claimed_at"):
        if closed.get(k) is not None and not TS_RE.match(str(closed[k])):
            errs.append(f"[closed].{k} must be a UTC timestamp such as 2026-09-30T08:15:00Z")
    return errs


def cmd_event(a):
    """Log what happened to an item after its work: its merge, the post-merge verify, an escape, an intervention."""
    if not ID_RE.match(a.id):
        sys.exit(f"{a.id}: not an item id")
    if a.caused_by and not ID_RE.match(a.caused_by):
        sys.exit(f"{a.caused_by}: not an item id")
    if a.kind == "merged" and not a.merge_sha:
        sys.exit("event merged needs --merge-sha")
    if a.kind == "post-verify" and a.rc is None:
        sys.exit("event post-verify needs --rc")
    c = load_claims().get(a.id) or {}
    fields = {"merged": {"merge_sha": resolve_rev(a.merge_sha), "conflicts": a.conflicts, "fixups": a.fixups},
              "post-verify": {"rc": a.rc}, "escape": {"caused_by": a.caused_by}, "intervention": {}}[a.kind]
    session = session_name(a.session, a.by, c.get("session"), c.get("by"))
    row = log_event(a.kind, a.id, session=session, executor=c.get("executor"), via=c.get("via"),
                    branch=a.branch or c.get("branch"), **fields)
    if row is None:
        print("not logged: a worker in a linked worktree logs no events")
    else:
        print(f"logged {a.kind} {a.id} to work/telemetry/events/{session}.jsonl")


# ---------------------------------------------------------------- views

def sev_key(it):
    return (SEV.index(it.get("severity", "p3")) if it.get("severity") in SEV else 9, it.get("title", ""))


def line(it, root_rel: Path):
    rel = it["_path"].relative_to(root_rel)
    lv = it.get("last_verified")
    tag = f" · verified {lv}" if lv else ""
    kind = "" if it["kind"] == "gap" else f" [{it['kind']}]"
    size = f" · size {it['size']}" if it.get("size") else ""
    hold = f" · **on hold:** {it['hold']}" if it.get("hold") else ""
    return f"- **{it['severity'].upper()}** [{it['id']}]({rel}) {it['title']}{kind}{size}{tag}{hold}"


def render_root(root_key: str, items):
    root = ROOTS[root_key]
    today = max((str(i.get("updated") or i.get("created") or "") for i in items), default="")  # deterministic: newest item date
    opened = [i for i in items if i.get("status") in OPEN]
    verified = [i for i in opened if i.get("triage") == "verified"]
    unverified = [i for i in opened if i.get("triage") != "verified"]
    parked = [i for i in items if i.get("status") == "parked"]
    closed = [i for i in items if i.get("status") not in OPEN and i.get("status") != "parked"]
    by_sub = defaultdict(list)
    for it in verified:
        by_sub[it["subsystem"][0]].append(it)
    out = [f"# roko work status{' (local)' if root_key == 'local' else ''}", "", GEN_NOTE, "",
           f"As of {today} (newest item update), from `{root.relative_to(REPO)}/items/`. "
           f"{len(opened)} open ({len(verified)} verified, {len(unverified)} unverified imports) · {len(closed)} closed · "
           f"{len(parked)} parked (not planned; in `parked/`, revive with `work.py unpark <id>`). "
           "Format and rules: `work/README.md`.", "",
           "Kinds: " + ", ".join(f"{k} {v}" for k, v in sorted(Counter(i['kind'] for i in opened).items())), ""]
    out += ["## Open — verified", ""]
    for sub in sorted(by_sub, key=lambda s: (min(sev_key(i) for i in by_sub[s]), s)):
        out.append(f"### {sub}")
        out += [line(i, root) for i in sorted(by_sub[sub], key=sev_key)]
        out.append("")
    by_sub_u = defaultdict(list)
    for it in unverified:
        by_sub_u[it["subsystem"][0]].append(it)
    if unverified:
        sev_counts = Counter(i.get("severity") for i in unverified)
        out += ["## Open — unverified imports", "",
                f"{len(unverified)} imported items have not been checked against current code yet "
                f"({', '.join(f'{s} {sev_counts[s]}' for s in SEV if sev_counts[s])}). "
                "They are listed in `TRIAGE.md`; verify one, then set `triage = \"verified\"` or close it with evidence.", "",
                "| Subsystem | Unverified |", "|---|---|"]
        out += [f"| {sub} | {len(by_sub_u[sub])} |" for sub in sorted(by_sub_u, key=lambda s: -len(by_sub_u[s]))]
        out.append("")
    tr = [f"# Triage queue{' (local)' if root_key == 'local' else ''}", "", GEN_NOTE, "",
          f"{len(unverified)} open items imported without verification, highest severity first within each subsystem.", ""]
    for sub in sorted(by_sub_u, key=lambda s: (min(sev_key(i) for i in by_sub_u[s]), s)):
        tr.append(f"### {sub} ({len(by_sub_u[sub])})")
        tr += [line(i, root) for i in sorted(by_sub_u[sub], key=sev_key)]
        tr.append("")
    (root / "TRIAGE.md").write_text("\n".join(tr) + "\n")
    out += ["## Recently closed", ""]
    recent = sorted(closed, key=lambda i: str((i.get("closed") or {}).get("at") or i.get("updated") or ""), reverse=True)[:30]
    out += [f"- [{i['id']}]({i['_path'].relative_to(root)}) {i['title']} — {i['status']}" for i in recent] or ["- none"]
    (root / "STATUS.md").write_text("\n".join(out) + "\n")

    top = [i for i in verified if i.get("kind") != "decision" and i.get("severity") in ("p0", "p1")]
    top = sorted(top, key=sev_key)[:40]
    cl = ["# Open now (p0/p1, verified)", "", GEN_NOTE, "",
          f"{len(top)} of {len(verified)} verified open items. Full list: `STATUS.md`. Add items per `work/README.md`.", ""]
    cl += [line(i, root) for i in top] or ["- none"]
    (root / "CLAUDE-OPEN.md").write_text("\n".join(cl) + "\n")

    decs = sorted([i for i in opened if i.get("kind") in ("decision", "question")], key=sev_key)
    dl = ["# Open decisions", "", GEN_NOTE, "", f"{len(decs)} open.", ""]
    dl += [line(i, root) for i in decs] or ["- none"]
    (root / "DECISIONS.md").write_text("\n".join(dl) + "\n")

    drift = compute_drift(items)
    (root / "DRIFT.md").write_text("\n".join(render_drift(root, items, drift, head_rev())) + "\n")
    if root_key == "work":
        render_now(root, opened, drift)
    return len(opened), len(verified), len(unverified), len(closed), len(parked)


def now_key(it):
    rank = it.get("rank")
    return (rank if isinstance(rank, int) else 10**6,) + sev_key(it)


def render_now(root: Path, opened, drift=None):
    goals = load_goals()
    out = ["# Now", "", GEN_NOTE, "",
           "What to work on next: the top checked, open items of each goal, highest-priority goal first. "
           "Reorder or change goals in `goals.toml`; pin an item higher with `rank = 1` (lower first).", ""]
    summary = drift_summary(drift or {})
    if summary:
        out += [f"**Drift:** {summary}. Re-check them before relying on this list: `DRIFT.md`.", ""]
    for n, g in enumerate(goals, 1):
        mine = [i for i in opened if i.get("goal") == g["key"]]
        active = sorted((i for i in mine if i.get("status") == "in_progress"), key=now_key)
        blocked = [i for i in mine if i.get("status") == "blocked"]
        waiting = [i for i in mine if i.get("status") == "open"]
        held = [i for i in waiting if i.get("hold")]
        ready = sorted((i for i in waiting if i.get("triage") == "verified" and not i.get("hold")), key=now_key)
        top = ready[: int(g.get("now", 3))]
        unchecked = len([i for i in waiting if i.get("triage") != "verified" and not i.get("hold")])
        out += [f"## {n}. {g['title']}", ""]
        out += [line(i, root) for i in top] or ["- nothing checked and open"]
        rest = [f"{len(ready) - len(top)} more open"]
        rest += [f"in progress: {', '.join(i['id'] for i in active)}"] if active else []
        rest += [f"{len(blocked)} blocked"] if blocked else []
        rest += [f"on hold: {', '.join(i['id'] for i in held)}"] if held else []
        rest += [f"{unchecked} unchecked (`TRIAGE.md`)"] if unchecked else []
        out += ["", f"_{' · '.join(rest)} · `goal = \"{g['key']}\"`_", ""]
    later = [i for i in opened if not i.get("goal")]
    out += [f"{len(later)} open items have no goal (later); they are listed in `STATUS.md`."]
    (root / "NOW.md").write_text("\n".join(out) + "\n")


# ---------------------------------------------------------------- editing items

def tomlstr(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ") + '"'


def index():
    return {it["id"]: it for key in ROOTS for it in load(key)[0]}


def edit_front(path: Path, fn) -> str:
    m = re.match(r"(\+\+\+\n)(.*?)(\n\+\+\+\n?)(.*)", path.read_text(), re.S)
    return m.group(1) + fn(m.group(2)) + m.group(3) + m.group(4)


def move(it, text: str, sub: str):
    dest = ROOTS[it["_root"]] / sub / it["_path"].name
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(text)
    if dest != it["_path"]:
        it["_path"].unlink()


def split_front(fm: str):
    """(top-level lines, [table blocks]); each block is a list of lines starting with its [header]."""
    top, blocks, cur, inq = [], [], None, None
    for ln in fm.split("\n"):
        if inq is None and re.match(r"^\[\[?[a-z_.]+\]\]?\s*$", ln):
            cur = [ln]
            blocks.append(cur)
            continue
        (cur if cur is not None else top).append(ln)
        for q in ('"""', "'''"):
            if ln.count(q) % 2 == 1:
                inq = None if inq == q else (q if inq is None else inq)
    return top, blocks


def join_front(top, blocks) -> str:
    top = list(top)
    while top and not top[-1].strip():
        top.pop()
    parts = ["\n".join(top)]
    for b in blocks:
        b = list(b)
        while b and not b[-1].strip():
            b.pop()
        parts.append("\n".join(b))
    return "\n\n".join(parts)


def set_key(top, key: str, value: str, after: str | None = None):
    """Replace `key = …` (single- or multi-line array) in the top-level lines, or insert it after `after`."""
    for i, ln in enumerate(top):
        if ln.startswith(f"{key} = "):
            j = i
            if ln.count("[") > ln.count("]"):
                while j + 1 < len(top) and not top[j].rstrip().endswith("]"):
                    j += 1
                    if top[j].strip().startswith("]"):
                        break
            top[i:j + 1] = [f"{key} = {value}"]
            return
    idx = next((k + 1 for k, ln in enumerate(top) if after and ln.startswith(f"{after} = ")), len(top))
    top.insert(idx, f"{key} = {value}")


def closed_value(key: str, v) -> str:
    """A [closed] value in TOML: `at` is a date, `forced` a boolean, everything else a string."""
    if key == "at":
        return str(v)
    if isinstance(v, bool):
        return "true" if v else "false"
    return tomlstr(str(v))


def rewrite_item(it, *, status=None, closed=None, verify=None, anchors=None, duplicate_of=None,
                 verified=False, rev=None, note=None, today=None):
    """Apply field changes to one item file; validates the result parses. Returns the new text."""
    today = today or dt.date.today().isoformat()
    m = re.match(r"(\+\+\+\n)(.*?)(\n\+\+\+\n?)(.*)", it["_path"].read_text(), re.S)
    top, blocks = split_front(m.group(2))
    body = m.group(4)
    if status:
        set_key(top, "status", f'"{status}"')
    set_key(top, "updated", today)
    if verified:
        set_key(top, "triage", '"verified"')
        set_key(top, "last_verified", today, after="updated")
        if rev:
            set_key(top, "last_verified_rev", f'"{rev}"', after="last_verified")
    if anchors is not None:
        set_key(top, "anchors", "[" + ", ".join(tomlstr(a) for a in anchors) + "]")
    if duplicate_of:
        for i, ln in enumerate(top):
            if ln.startswith("links = "):
                top[i] = re.sub(r'duplicate_of = "[^"]*"', f'duplicate_of = "{duplicate_of}"', ln)
    if verify is not None:
        rest = [b for b in blocks if b[0].strip() != "[[verify]]"]
        repro = [b for b in rest if b[0].strip() == "[[repro]]"]
        other = [b for b in rest if b[0].strip() != "[[repro]]"]
        blocks = repro + [["[[verify]]", f"command = {tomlstr(c)}"] for c in verify] + other
    if closed:
        top = [ln for ln in top if not ln.startswith("hold = ")]  # a closed item is no longer on hold
        blocks = [b for b in blocks if b[0].strip() != "[closed]"]
        blocks.append(["[closed]"] + [f"{k} = {closed_value(k, v)}" for k, v in closed.items() if v is not None and v != ""])
    if note:
        body = body.rstrip("\n") + "\n\n" + note.strip() + "\n"
    fm = join_front(top, blocks)
    tomllib.loads(fm)  # raise before writing anything broken
    return m.group(1) + fm + m.group(3) + body


def close_item(it, *, status="done", evidence="", commit=None, run_id=None, by=None, duplicate_of=None, note=None,
               executor=None, via=None, model=None, assist=None, forced=None, source="live", session=None):
    """Close `it`. [closed] gets the claim's executor, via, size and claimed_at (read from the main checkout, so this
    works in a worktree too); an `executor` or `via` given here wins over the claim's. In the main checkout the
    closure is logged as a `closed` event and the claim is deleted."""
    today = dt.date.today().isoformat()
    claim = item_claim(it["id"])
    executor, via = executor or claim.get("executor"), via or claim.get("via")
    closed = {"at": today, "at_ts": utc_ts(), "commit": commit, "run_id": run_id, "by": by, "executor": executor,
              "via": via, "size": claim.get("size"), "claimed_at": claim.get("claimed_at"), "model": model,
              "assist": assist, "forced": forced, "evidence": evidence}
    text = rewrite_item(it, status=status, closed=closed, duplicate_of=duplicate_of, verified=True,
                        rev=head_rev() or None, note=note, today=today)
    it["_path"].write_text(text)
    log_event("closed", it["id"], session=session or session_name(None, claim.get("session"), claim.get("by")),
              executor=executor, via=via, branch=claim.get("branch"), source=source, status=status, commit=commit,
              run_id=run_id, forced=forced)
    f = claims_dir() / f"{it['id']}.json"
    if f.exists() and in_main_checkout():
        f.unlink()


def resolve_rev(rev: str | None) -> str | None:
    if not rev:
        return None
    return git("rev-parse", "--short=9", rev).strip() or rev


def cmd_close(a):
    idx = index()
    it = idx.get(a.id)
    if it is None or it.get("status") not in OPEN:
        sys.exit(f"{a.id}: not found or not open")
    if a.status == "done" and not a.force:
        state = static_verify_state(it)
        if state == "red":
            sys.exit(f"{a.id}: the static part of its [[verify]] fails; fix it or pass --force with a reason in --evidence")
    if a.status == "superseded" and not (a.duplicate_of or a.evidence):
        sys.exit("superseded needs --duplicate-of or --evidence")
    claim = item_claim(a.id)
    close_item(it, status=a.status, evidence=a.evidence, commit=resolve_rev(a.commit), run_id=a.run_id,
               by=a.by, duplicate_of=a.duplicate_of, executor=a.executor, via=a.via, model=a.model, assist=a.assist,
               forced=bool(a.force), session=session_name(a.session, a.by, claim.get("session"), claim.get("by")))
    print(f"{a.id}: {a.status}")


def sync_candidates(items):
    """[(item, kind, detail)] for open items that a commit trailer or a passed plan task says are closed."""
    opened = {i["id"]: i for i in items if i.get("status") in OPEN}
    out = []
    for sha, date, subject, body, _ in commit_log(names=False):
        for m in CLOSE_RE.finditer(subject + "\n" + body):
            for iid in ID_ANY.findall(m.group(1)):
                it = opened.get(iid)
                if it and date >= str(it.get("created") or ""):
                    out.append((it, "commit", (sha, subject)))
    for iid, rows in plan_closes().items():
        it = opened.get(iid)
        for plan, task, verdict, run_id in rows:
            if it and verdict == "passed":
                out.append((it, "plan", (plan, task, run_id)))
    seen, uniq = set(), []
    for c in out:
        if c[0]["id"] not in seen:
            seen.add(c[0]["id"])
            uniq.append(c)
    return uniq


def cmd_sync(a, quiet=False):
    items = [i for k in ROOTS for i in load(k)[0]]
    if not a.dry_run:
        prune_claims()
    # Its closures are logged as `reconciled`, under the syncing session (the commit hook passes its session id).
    session = session_name(getattr(a, "session", None), getattr(a, "hook_session", None), "sync")
    closed, conflicts = [], []
    for it, kind, det in sync_candidates(items):
        state = static_verify_state(it)
        where = f"commit {det[0]} ({det[1][:70]})" if kind == "commit" else f"plan task {det[0]}#{det[1]} (run {det[2]})"
        if state == "red":
            conflicts.append(f"{it['id']}: {where} says it closes it, but the static part of its [[verify]] fails")
            continue
        if not a.dry_run:
            if kind == "commit":
                # A commit closure keeps its claim's executor; without a claim, nobody knows who did the work.
                close_item(it, commit=det[0], by="commit trailer", evidence=f"Closed by {det[0]}: {det[1]}",
                           executor=item_claim(it["id"]).get("executor") or "unknown", forced=False,
                           source="reconciled", session=session)
            else:
                close_item(it, run_id=det[2], by=f"plan:{det[0]}#{det[1]}",
                           evidence=f"Plan task {det[0]}#{det[1]} declares closes = [\"{it['id']}\"] and passed its gates (Graph checkpoint verdict: passed).",
                           executor="roko-plan", via="roko-plan", forced=False, source="reconciled", session=session)
        closed.append(f"{it['id']}: {'would close' if a.dry_run else 'closed'} ({where})")
    if not quiet or closed or conflicts:
        for s in closed + conflicts:
            print(s)
        if not closed and not conflicts:
            print("nothing to sync")
    return closed, conflicts


def cmd_drift(a):
    items = [i for i in load("work")[0]]
    drift = compute_drift(items, stale_days=a.stale_days)
    if a.json:
        by_id = {i["id"]: i for i in items}
        rows = []
        for iid, d in drift.items():
            it = by_id[iid]
            rows.append({"id": iid, "title": it["title"], "status": it["status"], "severity": it["severity"],
                         "goal": it.get("goal"), "path": str(it["_path"].relative_to(REPO)), "head": head_rev(),
                         "since": it.get("last_verified_rev") or _item_since(it), **{k: v for k, v in d.items()}})
        json.dump(rows, sys.stdout, indent=1, default=list)
        print()
        return
    print(drift_summary(drift) or "no drift")
    for iid, d in sorted(drift.items()):
        flags = [k for k in ("claimed", "plan_passed", "gone", "touched", "mentioned") if d[k]] + (["stale"] if d["stale"] else [])
        print(f"  {iid}: {', '.join(flags)}")


def touched_report(rev: str, items) -> list[str]:
    if ".." in rev:
        base, tip = rev.split("..", 1)
        tip = tip or "HEAD"
        msgs = git("log", "--format=%h %s%n%b", f"{base}..{tip}")
    else:
        base, tip = f"{rev}^", rev
        msgs = git("log", "-1", "--format=%h %s%n%b", rev)
    files = set(git("diff", "--name-only", base, tip).split()) if git_ok("rev-parse", "--verify", "-q", base) else \
        set(git("show", "--format=", "--name-only", tip).split())
    opened = [i for i in items if i.get("status") in OPEN]
    edited = {i["id"] for i in items if str(i["_path"].relative_to(REPO)) in files}  # the commit updated the item itself
    hit, lines = [], []
    for it in opened:
        paths = [p for p, _ in (anchor_parts(a) for a in it.get("anchors") or []) if p]
        if it["id"] not in edited and any(f == p or f.startswith(p + "/") for p in paths for f in files):
            hit.append(it)
    claimed = {iid for m in CLOSE_RE.finditer(msgs) for iid in ID_ANY.findall(m.group(1))}
    mentioned = set(ID_ANY.findall(msgs)) - claimed
    by_id = {i["id"]: i for i in items}
    for iid in sorted(claimed):
        it = by_id.get(iid)
        if it:
            lines.append(f"closes {iid} ({it['status']}): {it['title']}")
    for it in sorted(hit, key=sev_key):
        if it["id"] not in claimed:
            lines.append(f"touched {it['id']} [{it['severity']}] {it['title']} — {it['_path'].relative_to(REPO)}")
    for iid in sorted(mentioned - edited):
        it = by_id.get(iid)
        if it and it["id"] not in {h["id"] for h in hit}:
            lines.append(f"mentions {iid} ({it['status']}): {it['title']}")
    return lines


def cmd_touched(a):
    items = [i for k in ROOTS for i in load(k)[0]]
    for ln in touched_report(a.rev, items) or ["no open items touched"]:
        print(ln)


def cmd_verify(a):
    items = [i for k in ROOTS for i in load(k)[0]]
    if a.closed_since:
        sel = [i for i in items if i.get("status") == "done" and str((i.get("closed") or {}).get("at") or "") >= a.closed_since]
    else:
        sel = [i for i in items if i["id"] in set(a.ids)]
    bad = 0
    for it in sel:
        for v in it.get("verify") or []:
            cmd = static_prefix(v["command"]) if a.static_only else v["command"]
            if not cmd:
                continue
            rc = run_shell(cmd, timeout=3600)
            bad += rc != 0
            print(f"{'PASS' if rc == 0 else 'FAIL'} {it['id']} ({it['status']}): {cmd[:140]}")
        if not it.get("verify"):
            print(f"NONE {it['id']} ({it['status']}): no [[verify]] command")
    sys.exit(1 if bad else 0)


def cmd_hook(a):
    """Claude Code PostToolUse adapter: after a successful `git commit`, sync closures and list touched items."""
    try:
        payload = json.load(sys.stdin)
        cmd = ((payload.get("tool_input") or {}).get("command") or "")
        if not re.search(r"\bgit\b[^|;&]*\bcommit\b", cmd) or "--dry-run" in cmd:
            return
        m = re.search(r"\bcd\s+(\S+)\s*&&", cmd)
        cwd = Path(payload.get("cwd") or REPO)
        if m:
            cwd = (cwd / m.group(1).strip("'\"")).resolve()
        top = subprocess.run(["git", "rev-parse", "--show-toplevel"], cwd=cwd, capture_output=True, text=True).stdout.strip()
        if not top or not (Path(top) / "work" / "items").is_dir():
            return
        set_repo(top)
        resp = payload.get("tool_response")
        out = resp if isinstance(resp, str) else "\n".join(str((resp or {}).get(k) or "") for k in ("stdout", "output", "stderr"))
        made = re.search(r"^\[[^\]\n]*?\s([0-9a-f]{7,40})\]", out, re.M)  # git commit prints "[branch abc1234] subject"
        if made:
            rev = made.group(1)
        elif re.search(r"\s(?:-q|--quiet)\b", cmd) and time.time() - int(git("log", "-1", "--format=%ct").strip() or 0) < 120:
            rev = head_rev()  # a quiet commit prints nothing; accept a HEAD made in the last two minutes
        else:
            return  # no commit was made by this command: say nothing
        import contextlib, io
        with contextlib.redirect_stdout(io.StringIO()):
            closed, conflicts = cmd_sync(argparse.Namespace(dry_run=False, hook_session=payload.get("session_id")),
                                         quiet=True)
        report = touched_report(rev, [i for k in ROOTS for i in load(k)[0]])
        if not (closed or conflicts or report):
            return
        msg = ["Work graph check for this commit (tools/work.py):"]
        msg += [f"- {c}" for c in closed] + [f"- CONFLICT {c}" for c in conflicts]
        msg += [f"- {r}" for r in report[:15]] + ([f"- … {len(report) - 15} more: tools/work.py touched --rev HEAD"] if len(report) > 15 else [])
        msg.append("If this commit fixed an item listed as touched, close it now: tools/work.py close <id> --commit HEAD "
                   "--evidence \"…\" (or add `Closes: <id>` to the next commit message). If it only changed the code an item "
                   "describes, re-check the item. Closures made here are uncommitted edits under work/; commit them with your "
                   "next commit, then run tools/work.py render.")
        msg[0] = f"Work graph check for commit {rev} (tools/work.py):"
        print(json.dumps({"hookSpecificOutput": {"hookEventName": "PostToolUse", "additionalContext": "\n".join(msg)}}))
    except Exception:  # noqa: BLE001 - a hook must never break the session
        return


# ---------------------------------------------------------------- sweep: apply agent verdicts

PROSE = re.compile(r"\((?:the |test |a |or |e\.g|proxy|better|interim|must |see |settled|live |requires|then )|interim static|A named test|; better|must add\)|\bshould\b", re.I)
CT = re.compile(r"^cargo test -p (?P<crate>[a-z0-9_-]+)(?P<flags>(?: --(?:lib|bins?(?: [a-z0-9_-]+)?|test [A-Za-z0-9_-]+|all-features|release))*)(?: (?P<filt>[A-Za-z0-9_:]+))?(?: --.*)?$")


def strip_note(s: str) -> str:
    """Drop a trailing prose note from a suggested command: 'cmd  (the fix must add …)' → 'cmd'."""
    q, depth = None, 0
    for i, c in enumerate(s):
        if q:
            if c == q:
                q = None
            continue
        if c in "'\"":
            q = c
            continue
        if c == "(":
            if depth == 0 and i and s[i - 1] == " " and re.match(r"\((?:[a-z]+ ){1,}|\(e\.g|\(proxy|\(or |\(a ", s[i:]):
                return s[:i].rstrip(" ;,")
            depth += 1
        elif c == ")":
            depth -= 1
        elif depth == 0 and (s.startswith("; ", i) or s.startswith(", plus ", i) or s.startswith(". The current", i)
                             or (s.startswith(". ", i) and s[i + 2:i + 3].isupper())):
            return s[:i].rstrip(" ;,")
    return s


def cargo_guard(seg: str) -> str | None:
    m = CT.match(seg.strip())
    if not m:
        return None
    crate, flags, filt = m.group("crate"), m.group("flags") or "", m.group("filt")
    tm = re.search(r"--test ([A-Za-z0-9_-]+)", flags)
    if not filt:
        return f"test -f crates/{crate}/tests/{tm.group(1)}.rs" if tm else None
    name = filt.split("::")[-1]
    return f"grep -rqE 'fn {name}[A-Za-z0-9_]*' crates/{crate}/" if name.endswith("_") else f"grep -rqw 'fn {name}' crates/{crate}/"


def validate_suggestion(s: str, want_green: bool):
    """A suggested verify command is adopted only if it is a clean command whose static part is red now for an open item
    (green for a done one). A cargo-only command gets a `grep 'fn <test>'` guard so an unwritten test cannot pass vacuously."""
    for cand in (s, strip_note(s)):
        cand = cand.strip()
        if not cand or PROSE.search(cand) or cand[0].isupper():
            continue
        parts = split_and(cand)
        static = static_prefix(cand)
        if not static:
            g = cargo_guard(parts[0]) if parts else None
            if not g:
                continue
            cand, static = f"{g} && {cand}", g
        if (run_shell(static, 60) == 0) == want_green:
            return cand
    return None


def valid_anchor(a: str) -> bool:
    path, sym = anchor_parts(a)
    if not path:
        return True
    p = REPO / path
    if not p.exists():
        return False
    if sym and p.is_file():
        return re.search(r"\b" + re.escape(sym) + r"\b", p.read_text(errors="replace")) is not None
    return True


def cmd_apply_verdicts(a):
    """Apply one JSON object per line: {id, verdict, evidence, commit, duplicate_of, note, anchors, verify_sound, verify_suggestion}.
    Verdicts: done | in_progress | open | partial | superseded | duplicate | unclear (see tools/work_sweep_brief.md)."""
    snap = {r["id"]: r for r in json.load(open(a.snapshot))}
    verdicts = {}
    for f in a.files:
        for ln in open(f):
            if ln.strip():
                o = json.loads(ln)
                verdicts[o["id"]] = o
    idx = index()
    by = a.by or f"work sweep {dt.date.today().isoformat()} (static check)"
    stats = Counter()
    for iid, o in verdicts.items():
        it, seen = idx.get(iid), snap.get(iid, {})
        if it is None:
            print(f"SKIP {iid}: no such item")
            continue
        if seen and it["status"] != seen.get("status"):
            print(f"SKIP {iid}: status changed since the snapshot ({seen.get('status')} → {it['status']})")
            continue
        v = o["verdict"]
        status = {"done": "done", "duplicate": "superseded", "superseded": "superseded", "in_progress": "in_progress"}.get(v)
        if it["status"] == "in_progress" and v in ("open", "partial"):
            status = "open"
        notes = []
        cur = [x.get("command", "") for x in it.get("verify") or []]
        verify = None
        sug = (o.get("verify_suggestion") or "").strip()
        if sug and (o.get("verify_sound") is False or not cur):
            good = validate_suggestion(sug, want_green=v in ("done", "in_progress"))
            if good:
                verify = [good]
            elif o.get("verify_sound") is False:
                notes.append(f"The [[verify]] command is unsound. Proposed replacement, not yet validated: `{sug}`.")
        if verify is None and v in ("open", "partial"):
            passing = [c for c in cur if static_prefix(c) == c and run_shell(c, 60) == 0]
            if passing:
                verify = [c for c in cur if c not in passing]
                notes += [f"Removed [[verify]] `{c}`: it passes while the problem still exists." for c in passing]
        anchors = None
        if o.get("anchors"):
            good = [x for x in o["anchors"] if isinstance(x, str) and valid_anchor(x)]
            if any("/" in x for x in good) and good != it.get("anchors"):
                anchors = good
        closed = None
        if status in ("done", "superseded"):
            ev = o.get("evidence", "")
            if v == "duplicate":
                ev = f"Duplicate of {o.get('duplicate_of')} (the older item; keep that ID). {ev}"
            closed = {"at": dt.date.today().isoformat(), "commit": o.get("commit") if v == "done" else None, "by": by, "evidence": ev}
        note = (o.get("note") or "").strip()
        if note:
            today = dt.date.today().isoformat()
            notes.insert(0, note if today in note[:60] else f"Checked {today}: {note}")
        text = rewrite_item(it, status=status, closed=closed, verify=verify, anchors=anchors,
                            duplicate_of=o.get("duplicate_of") if v == "duplicate" else None,
                            verified=v != "unclear", rev=seen.get("head"), note="\n\n".join(notes) or None)
        stats[v] += 1
        if not a.dry_run:
            it["_path"].write_text(text)
    print(("would apply " if a.dry_run else "applied ") + json.dumps(stats))


# ---------------------------------------------------------------- new / park

BODY_TEMPLATE = """## Problem

What is wrong or missing, as observed: the symptom, the command or input that shows it, the actual vs expected result.

## Why it matters

Which goal this serves (see work/goals.toml) and what it unblocks or puts at risk. Related items by ID.

## Where

The code involved (explain the anchors above): files, functions, and the entry point that reaches them.

## Current state

What exists today, what is already partly fixed (with commits), and what is known about the cause.

## Plan

The suggested approach, step by step. If there is a real design choice, name the options and the trade-off.

## Done when

Observable acceptance criteria. The [[verify]] command must fail before the fix and pass after it.

## Notes

Constraints (files not to touch, decisions already made, risky areas), and anything a worker should know first.
"""


def cmd_new(a):
    created = a.created or dt.date.today().isoformat()
    iid = make_id(a.kind, a.title, created, a.source)
    root = ROOTS[a.root] / "items"
    root.mkdir(parents=True, exist_ok=True)
    path = root / f"{iid}-{slug(a.title)}.md"
    if path.exists():
        iid = make_id(a.kind, a.title, created, a.source, 8)
        path = root / f"{iid}-{slug(a.title)}.md"
    subs = [s.strip() for s in (a.subsystem or "unknown").split(",") if s.strip()]
    fm = [
        "+++", f'id = "{iid}"', f'kind = "{a.kind}"', f"title = {tomlstr(a.title)}", f'status = "{a.status}"',
        f'triage = "{a.triage}"', f'severity = "{a.severity}"', "subsystem = [" + ", ".join(tomlstr(s) for s in subs) + "]",
        f"created = {created}", f"updated = {dt.date.today().isoformat()}",
    ]
    if a.triage == "verified":
        fm.append(f"last_verified = {dt.date.today().isoformat()}")
    fm += [f"source = {tomlstr(a.source)}", "anchors = []",
           'links = { depends_on = [], blocks = [], related = [], supersedes = [], duplicate_of = "" }', "+++", "", BODY_TEMPLATE]
    path.write_text("\n".join(fm))
    print(path.relative_to(REPO))


def cmd_park(a):
    today, idx = dt.date.today().isoformat(), index()
    for iid in a.ids:
        it = idx.get(iid)
        if it is None or it.get("status") not in OPEN:
            sys.exit(f"{iid}: not found or not open")
        prev = it["status"]

        def edit(fm):
            fm = re.sub(r'^status = "[a-z_]+"$', 'status = "parked"', fm, count=1, flags=re.M)
            fm = re.sub(r"^updated = .*$", f"updated = {today}", fm, count=1, flags=re.M)
            return fm + f'\n\n[parked]\nat = {today}\nfrom_status = "{prev}"\nreason = {tomlstr(a.reason)}'

        move(it, edit_front(it["_path"], edit), "parked")
    print(f"parked {len(a.ids)}")


def cmd_unpark(a):
    today, idx = dt.date.today().isoformat(), index()
    for iid in a.ids:
        it = idx.get(iid)
        if it is None or it.get("status") != "parked":
            sys.exit(f"{iid}: not found or not parked")
        prev = (it.get("parked") or {}).get("from_status", "open")

        def edit(fm):
            fm = re.sub(r"\n*\[parked\]\n(?:[a-z_]+ = [^\n]*(?:\n|$))*", "\n\n", fm)
            fm = re.sub(r'^status = "parked"$', f'status = "{prev}"', fm, count=1, flags=re.M)
            fm = re.sub(r"^updated = .*$", f"updated = {today}", fm, count=1, flags=re.M)
            return re.sub(r"\n{3,}", "\n\n", fm).rstrip("\n")

        move(it, edit_front(it["_path"], edit), "items")
    print(f"unparked {len(a.ids)}")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    sp = ap.add_subparsers(dest="cmd", required=True)
    p = sp.add_parser("id"); p.add_argument("--kind", required=True, choices=PREFIX); p.add_argument("--title", required=True)
    p.add_argument("--created", required=True); p.add_argument("--source", required=True)
    p = sp.add_parser("new"); p.add_argument("--kind", required=True, choices=PREFIX); p.add_argument("--title", required=True)
    p.add_argument("--source", required=True); p.add_argument("--created"); p.add_argument("--root", default="work", choices=ROOTS)
    p.add_argument("--subsystem"); p.add_argument("--severity", default="p2", choices=SEV)
    p.add_argument("--status", default="open", choices=sorted(STATUSES - {"parked"})); p.add_argument("--triage", default="unverified", choices=sorted(TRIAGE))
    p = sp.add_parser("park"); p.add_argument("ids", nargs="+"); p.add_argument("--reason", required=True)
    p = sp.add_parser("unpark"); p.add_argument("ids", nargs="+")
    p = sp.add_parser("close"); p.add_argument("id"); p.add_argument("--evidence", required=True)
    p.add_argument("--status", default="done", choices=["done", "wontfix", "superseded"]); p.add_argument("--commit")
    p.add_argument("--run-id"); p.add_argument("--by"); p.add_argument("--duplicate-of"); p.add_argument("--force", action="store_true")
    p.add_argument("--model", help="the model that did the work"); p.add_argument("--assist", help="a second executor that helped")
    p.add_argument("--executor", choices=EXECUTORS, help="who executed it, when its claim does not say")
    p.add_argument("--via", choices=VIAS, help="how it was picked up, when its claim does not say")
    p.add_argument("--session", help="the events file to log to (default: $WORK_SESSION, else --by)")
    p = sp.add_parser("sync"); p.add_argument("--dry-run", action="store_true")
    p = sp.add_parser("drift"); p.add_argument("--json", action="store_true"); p.add_argument("--stale-days", type=int, default=STALE_DAYS)
    p = sp.add_parser("touched"); p.add_argument("--rev", default="HEAD")
    p = sp.add_parser("verify"); p.add_argument("ids", nargs="*"); p.add_argument("--closed-since"); p.add_argument("--static-only", action="store_true")
    p = sp.add_parser("apply-verdicts"); p.add_argument("files", nargs="+"); p.add_argument("--snapshot", required=True)
    p.add_argument("--dry-run", action="store_true"); p.add_argument("--by")
    sp.add_parser("hook")
    p = sp.add_parser("next"); p.add_argument("--n", type=int, default=1); p.add_argument("--goal"); p.add_argument("--max-size", choices=SIZES)
    p.add_argument("--json", action="store_true")
    p = sp.add_parser("claim"); p.add_argument("ids", nargs="+"); p.add_argument("--by", required=True); p.add_argument("--branch")
    p.add_argument("--worktree"); p.add_argument("--force", action="store_true")
    p.add_argument("--session", help="the events file to log to (default: $WORK_SESSION, else --by)")
    p.add_argument("--executor", choices=EXECUTORS, help="who executes the item")
    p.add_argument("--via", choices=VIAS, help="how it was picked up")
    p.add_argument("--size", choices=SIZES, help="the size judged before work starts (default: the item's size)")
    p = sp.add_parser("release"); p.add_argument("ids", nargs="+")
    p.add_argument("--reason", choices=RELEASE_REASONS, help="why the item goes back unfinished")
    p.add_argument("--session", help="the events file to log to (default: $WORK_SESSION, else the claim's session)")
    sp.add_parser("claims")
    p = sp.add_parser("event", help="log a merge, post-merge verify, escape or intervention (main checkout only)")
    p.add_argument("kind", choices=["merged", "post-verify", "escape", "intervention"]); p.add_argument("id")
    p.add_argument("--merge-sha"); p.add_argument("--conflicts", type=int); p.add_argument("--fixups", type=int)
    p.add_argument("--rc", type=int); p.add_argument("--caused-by"); p.add_argument("--branch")
    p.add_argument("--session"); p.add_argument("--by")
    p = sp.add_parser("check"); p.add_argument("--strict", action="store_true", help="treat verify-command lint warnings as errors")
    p.add_argument("--lint", action="store_true", help="list verify-command lint warnings")
    sp.add_parser("render")
    a = ap.parse_args()
    simple = {"new": cmd_new, "park": cmd_park, "unpark": cmd_unpark, "close": cmd_close, "sync": cmd_sync, "drift": cmd_drift,
              "touched": cmd_touched, "verify": cmd_verify, "apply-verdicts": cmd_apply_verdicts, "hook": cmd_hook,
              "next": cmd_next, "claim": cmd_claim, "release": cmd_release, "claims": cmd_claims, "event": cmd_event}
    if a.cmd == "id":
        print(make_id(a.kind, a.title, a.created, a.source)); return
    if a.cmd in simple:
        simple[a.cmd](a); return
    all_errs, warns, total = [], [], 0
    for key in ROOTS:
        items, errs = load(key)
        errs += validate(items)
        all_errs += errs
        total += len(items)
        for it in items if a.cmd == "check" and (getattr(a, "lint", False) or getattr(a, "strict", False)) else []:
            if it.get("status") in OPEN:
                for v in it.get("verify") or []:
                    warns += [f"{it['_path'].relative_to(REPO)}: [[verify]] {w}" for w in lint_verify(v.get("command", ""))]
        if a.cmd == "render" and ROOTS[key].exists():
            print(key, "open/verified/unverified/closed/parked =", render_root(key, items))
    if a.cmd == "check" and getattr(a, "strict", False):
        all_errs += warns
    lint = a.cmd == "check" and getattr(a, "lint", False)
    hint = "" if lint or getattr(a, "strict", False) else " (list them: check --lint)"
    print(f"{total} items; {len(all_errs)} problems" + (f"; {len(warns)} verify-command warnings{hint}" if warns and a.cmd == "check" else ""))
    for e in all_errs[:200]:
        print("  ", e)
    if lint:
        for w in warns:
            print("   warning:", w)
    sys.exit(1 if all_errs else 0)


if __name__ == "__main__":
    main()
